//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var CharCreateData = newCharCreateDataTable("eqgo", "char_create_data", "")

type charCreateDataTable struct {
	mysql.Table

	// Columns
	ID           mysql.ColumnInteger
	Category     mysql.ColumnString
	Name         mysql.ColumnString
	AltName      mysql.ColumnString
	Description  mysql.ColumnString
	EqstrIDStart mysql.ColumnInteger
	EqstrIDEnd   mysql.ColumnInteger
	GameID       mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type CharCreateDataTable struct {
	charCreateDataTable

	EXCLUDED charCreateDataTable
}

func newCharCreateDataTable(schemaName, tableName, alias string) *CharCreateDataTable {
	return &CharCreateDataTable{
		charCreateDataTable: newCharCreateDataTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newCharCreateDataTableImpl("", "excluded", ""),
	}
}

func newCharCreateDataTableImpl(schemaName, tableName, alias string) charCreateDataTable {
	var (
		IDColumn           = mysql.IntegerColumn("id")
		CategoryColumn     = mysql.StringColumn("category")
		NameColumn         = mysql.StringColumn("name")
		AltNameColumn      = mysql.StringColumn("alt_name")
		DescriptionColumn  = mysql.StringColumn("description")
		EqstrIDStartColumn = mysql.IntegerColumn("eqstr_id_start")
		EqstrIDEndColumn   = mysql.IntegerColumn("eqstr_id_end")
		GameIDColumn       = mysql.IntegerColumn("game_id")
		allColumns         = mysql.ColumnList{IDColumn, CategoryColumn, NameColumn, AltNameColumn, DescriptionColumn, EqstrIDStartColumn, EqstrIDEndColumn, GameIDColumn}
		mutableColumns     = mysql.ColumnList{CategoryColumn, NameColumn, AltNameColumn, DescriptionColumn, EqstrIDStartColumn, EqstrIDEndColumn, GameIDColumn}
	)

	return charCreateDataTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		ID:           IDColumn,
		Category:     CategoryColumn,
		Name:         NameColumn,
		AltName:      AltNameColumn,
		Description:  DescriptionColumn,
		EqstrIDStart: EqstrIDStartColumn,
		EqstrIDEnd:   EqstrIDEndColumn,
		GameID:       GameIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}

func (a CharCreateDataTable) AS(alias string) *CharCreateDataTable {
	return newCharCreateDataTable(a.SchemaName(), a.TableName(), alias)
}

func (a CharCreateDataTable) SchemaName() string {
	return a.Table.SchemaName()
}

func (a CharCreateDataTable) TableName() string {
	return a.Table.TableName()
}
