//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var CharacterData = newCharacterDataTable("eqgo", "character_data", "")

type characterDataTable struct {
	mysql.Table

	// Columns
	ID                    mysql.ColumnInteger
	AccountID             mysql.ColumnInteger
	Name                  mysql.ColumnString
	LastName              mysql.ColumnString
	Title                 mysql.ColumnString
	Suffix                mysql.ColumnString
	ZoneID                mysql.ColumnInteger
	ZoneInstance          mysql.ColumnInteger
	Y                     mysql.ColumnFloat
	X                     mysql.ColumnFloat
	Z                     mysql.ColumnFloat
	Heading               mysql.ColumnFloat
	Gender                mysql.ColumnInteger
	Race                  mysql.ColumnInteger
	Class                 mysql.ColumnInteger
	Level                 mysql.ColumnInteger
	Deity                 mysql.ColumnInteger
	Birthday              mysql.ColumnInteger
	LastLogin             mysql.ColumnInteger
	TimePlayed            mysql.ColumnInteger
	Level2                mysql.ColumnInteger
	Anon                  mysql.ColumnInteger
	Gm                    mysql.ColumnInteger
	Face                  mysql.ColumnInteger
	HairColor             mysql.ColumnInteger
	HairStyle             mysql.ColumnInteger
	Beard                 mysql.ColumnInteger
	BeardColor            mysql.ColumnInteger
	EyeColor1             mysql.ColumnInteger
	EyeColor2             mysql.ColumnInteger
	DrakkinHeritage       mysql.ColumnInteger
	DrakkinTattoo         mysql.ColumnInteger
	DrakkinDetails        mysql.ColumnInteger
	AbilityTimeSeconds    mysql.ColumnInteger
	AbilityNumber         mysql.ColumnInteger
	AbilityTimeMinutes    mysql.ColumnInteger
	AbilityTimeHours      mysql.ColumnInteger
	Exp                   mysql.ColumnInteger
	ExpEnabled            mysql.ColumnInteger
	AaPointsSpent         mysql.ColumnInteger
	AaExp                 mysql.ColumnInteger
	AaPoints              mysql.ColumnInteger
	GroupLeadershipExp    mysql.ColumnInteger
	RaidLeadershipExp     mysql.ColumnInteger
	GroupLeadershipPoints mysql.ColumnInteger
	RaidLeadershipPoints  mysql.ColumnInteger
	Points                mysql.ColumnInteger
	CurHp                 mysql.ColumnInteger
	Mana                  mysql.ColumnInteger
	Endurance             mysql.ColumnInteger
	Intoxication          mysql.ColumnInteger
	Str                   mysql.ColumnInteger
	Sta                   mysql.ColumnInteger
	Cha                   mysql.ColumnInteger
	Dex                   mysql.ColumnInteger
	Int                   mysql.ColumnInteger
	Agi                   mysql.ColumnInteger
	Wis                   mysql.ColumnInteger
	ExtraHaste            mysql.ColumnInteger
	ZoneChangeCount       mysql.ColumnInteger
	Toxicity              mysql.ColumnInteger
	HungerLevel           mysql.ColumnInteger
	ThirstLevel           mysql.ColumnInteger
	AbilityUp             mysql.ColumnInteger
	LdonPointsGuk         mysql.ColumnInteger
	LdonPointsMir         mysql.ColumnInteger
	LdonPointsMmc         mysql.ColumnInteger
	LdonPointsRuj         mysql.ColumnInteger
	LdonPointsTak         mysql.ColumnInteger
	LdonPointsAvailable   mysql.ColumnInteger
	TributeTimeRemaining  mysql.ColumnInteger
	CareerTributePoints   mysql.ColumnInteger
	TributePoints         mysql.ColumnInteger
	TributeActive         mysql.ColumnInteger
	PvpStatus             mysql.ColumnInteger
	PvpKills              mysql.ColumnInteger
	PvpDeaths             mysql.ColumnInteger
	PvpCurrentPoints      mysql.ColumnInteger
	PvpCareerPoints       mysql.ColumnInteger
	PvpBestKillStreak     mysql.ColumnInteger
	PvpWorstDeathStreak   mysql.ColumnInteger
	PvpCurrentKillStreak  mysql.ColumnInteger
	Pvp2                  mysql.ColumnInteger
	PvpType               mysql.ColumnInteger
	ShowHelm              mysql.ColumnInteger
	GroupAutoConsent      mysql.ColumnInteger
	RaidAutoConsent       mysql.ColumnInteger
	GuildAutoConsent      mysql.ColumnInteger
	LeadershipExpOn       mysql.ColumnInteger
	RestTimer             mysql.ColumnInteger
	AirRemaining          mysql.ColumnInteger
	AutosplitEnabled      mysql.ColumnInteger
	Lfp                   mysql.ColumnInteger
	Lfg                   mysql.ColumnInteger
	Mailkey               mysql.ColumnString
	Xtargets              mysql.ColumnInteger
	Firstlogon            mysql.ColumnInteger
	EAaEffects            mysql.ColumnInteger
	EPercentToAa          mysql.ColumnInteger
	EExpendedAaSpent      mysql.ColumnInteger
	AaPointsSpentOld      mysql.ColumnInteger
	AaPointsOld           mysql.ColumnInteger
	ELastInvsnapshot      mysql.ColumnInteger
	DeletedAt             mysql.ColumnTimestamp
	IllusionBlock         mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type CharacterDataTable struct {
	characterDataTable

	NEW characterDataTable
}

// AS creates new CharacterDataTable with assigned alias
func (a CharacterDataTable) AS(alias string) *CharacterDataTable {
	return newCharacterDataTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CharacterDataTable with assigned schema name
func (a CharacterDataTable) FromSchema(schemaName string) *CharacterDataTable {
	return newCharacterDataTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CharacterDataTable with assigned table prefix
func (a CharacterDataTable) WithPrefix(prefix string) *CharacterDataTable {
	return newCharacterDataTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CharacterDataTable with assigned table suffix
func (a CharacterDataTable) WithSuffix(suffix string) *CharacterDataTable {
	return newCharacterDataTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCharacterDataTable(schemaName, tableName, alias string) *CharacterDataTable {
	return &CharacterDataTable{
		characterDataTable: newCharacterDataTableImpl(schemaName, tableName, alias),
		NEW:                newCharacterDataTableImpl("", "new", ""),
	}
}

func newCharacterDataTableImpl(schemaName, tableName, alias string) characterDataTable {
	var (
		IDColumn                    = mysql.IntegerColumn("id")
		AccountIDColumn             = mysql.IntegerColumn("account_id")
		NameColumn                  = mysql.StringColumn("name")
		LastNameColumn              = mysql.StringColumn("last_name")
		TitleColumn                 = mysql.StringColumn("title")
		SuffixColumn                = mysql.StringColumn("suffix")
		ZoneIDColumn                = mysql.IntegerColumn("zone_id")
		ZoneInstanceColumn          = mysql.IntegerColumn("zone_instance")
		YColumn                     = mysql.FloatColumn("y")
		XColumn                     = mysql.FloatColumn("x")
		ZColumn                     = mysql.FloatColumn("z")
		HeadingColumn               = mysql.FloatColumn("heading")
		GenderColumn                = mysql.IntegerColumn("gender")
		RaceColumn                  = mysql.IntegerColumn("race")
		ClassColumn                 = mysql.IntegerColumn("class")
		LevelColumn                 = mysql.IntegerColumn("level")
		DeityColumn                 = mysql.IntegerColumn("deity")
		BirthdayColumn              = mysql.IntegerColumn("birthday")
		LastLoginColumn             = mysql.IntegerColumn("last_login")
		TimePlayedColumn            = mysql.IntegerColumn("time_played")
		Level2Column                = mysql.IntegerColumn("level2")
		AnonColumn                  = mysql.IntegerColumn("anon")
		GmColumn                    = mysql.IntegerColumn("gm")
		FaceColumn                  = mysql.IntegerColumn("face")
		HairColorColumn             = mysql.IntegerColumn("hair_color")
		HairStyleColumn             = mysql.IntegerColumn("hair_style")
		BeardColumn                 = mysql.IntegerColumn("beard")
		BeardColorColumn            = mysql.IntegerColumn("beard_color")
		EyeColor1Column             = mysql.IntegerColumn("eye_color_1")
		EyeColor2Column             = mysql.IntegerColumn("eye_color_2")
		DrakkinHeritageColumn       = mysql.IntegerColumn("drakkin_heritage")
		DrakkinTattooColumn         = mysql.IntegerColumn("drakkin_tattoo")
		DrakkinDetailsColumn        = mysql.IntegerColumn("drakkin_details")
		AbilityTimeSecondsColumn    = mysql.IntegerColumn("ability_time_seconds")
		AbilityNumberColumn         = mysql.IntegerColumn("ability_number")
		AbilityTimeMinutesColumn    = mysql.IntegerColumn("ability_time_minutes")
		AbilityTimeHoursColumn      = mysql.IntegerColumn("ability_time_hours")
		ExpColumn                   = mysql.IntegerColumn("exp")
		ExpEnabledColumn            = mysql.IntegerColumn("exp_enabled")
		AaPointsSpentColumn         = mysql.IntegerColumn("aa_points_spent")
		AaExpColumn                 = mysql.IntegerColumn("aa_exp")
		AaPointsColumn              = mysql.IntegerColumn("aa_points")
		GroupLeadershipExpColumn    = mysql.IntegerColumn("group_leadership_exp")
		RaidLeadershipExpColumn     = mysql.IntegerColumn("raid_leadership_exp")
		GroupLeadershipPointsColumn = mysql.IntegerColumn("group_leadership_points")
		RaidLeadershipPointsColumn  = mysql.IntegerColumn("raid_leadership_points")
		PointsColumn                = mysql.IntegerColumn("points")
		CurHpColumn                 = mysql.IntegerColumn("cur_hp")
		ManaColumn                  = mysql.IntegerColumn("mana")
		EnduranceColumn             = mysql.IntegerColumn("endurance")
		IntoxicationColumn          = mysql.IntegerColumn("intoxication")
		StrColumn                   = mysql.IntegerColumn("str")
		StaColumn                   = mysql.IntegerColumn("sta")
		ChaColumn                   = mysql.IntegerColumn("cha")
		DexColumn                   = mysql.IntegerColumn("dex")
		IntColumn                   = mysql.IntegerColumn("int")
		AgiColumn                   = mysql.IntegerColumn("agi")
		WisColumn                   = mysql.IntegerColumn("wis")
		ExtraHasteColumn            = mysql.IntegerColumn("extra_haste")
		ZoneChangeCountColumn       = mysql.IntegerColumn("zone_change_count")
		ToxicityColumn              = mysql.IntegerColumn("toxicity")
		HungerLevelColumn           = mysql.IntegerColumn("hunger_level")
		ThirstLevelColumn           = mysql.IntegerColumn("thirst_level")
		AbilityUpColumn             = mysql.IntegerColumn("ability_up")
		LdonPointsGukColumn         = mysql.IntegerColumn("ldon_points_guk")
		LdonPointsMirColumn         = mysql.IntegerColumn("ldon_points_mir")
		LdonPointsMmcColumn         = mysql.IntegerColumn("ldon_points_mmc")
		LdonPointsRujColumn         = mysql.IntegerColumn("ldon_points_ruj")
		LdonPointsTakColumn         = mysql.IntegerColumn("ldon_points_tak")
		LdonPointsAvailableColumn   = mysql.IntegerColumn("ldon_points_available")
		TributeTimeRemainingColumn  = mysql.IntegerColumn("tribute_time_remaining")
		CareerTributePointsColumn   = mysql.IntegerColumn("career_tribute_points")
		TributePointsColumn         = mysql.IntegerColumn("tribute_points")
		TributeActiveColumn         = mysql.IntegerColumn("tribute_active")
		PvpStatusColumn             = mysql.IntegerColumn("pvp_status")
		PvpKillsColumn              = mysql.IntegerColumn("pvp_kills")
		PvpDeathsColumn             = mysql.IntegerColumn("pvp_deaths")
		PvpCurrentPointsColumn      = mysql.IntegerColumn("pvp_current_points")
		PvpCareerPointsColumn       = mysql.IntegerColumn("pvp_career_points")
		PvpBestKillStreakColumn     = mysql.IntegerColumn("pvp_best_kill_streak")
		PvpWorstDeathStreakColumn   = mysql.IntegerColumn("pvp_worst_death_streak")
		PvpCurrentKillStreakColumn  = mysql.IntegerColumn("pvp_current_kill_streak")
		Pvp2Column                  = mysql.IntegerColumn("pvp2")
		PvpTypeColumn               = mysql.IntegerColumn("pvp_type")
		ShowHelmColumn              = mysql.IntegerColumn("show_helm")
		GroupAutoConsentColumn      = mysql.IntegerColumn("group_auto_consent")
		RaidAutoConsentColumn       = mysql.IntegerColumn("raid_auto_consent")
		GuildAutoConsentColumn      = mysql.IntegerColumn("guild_auto_consent")
		LeadershipExpOnColumn       = mysql.IntegerColumn("leadership_exp_on")
		RestTimerColumn             = mysql.IntegerColumn("RestTimer")
		AirRemainingColumn          = mysql.IntegerColumn("air_remaining")
		AutosplitEnabledColumn      = mysql.IntegerColumn("autosplit_enabled")
		LfpColumn                   = mysql.IntegerColumn("lfp")
		LfgColumn                   = mysql.IntegerColumn("lfg")
		MailkeyColumn               = mysql.StringColumn("mailkey")
		XtargetsColumn              = mysql.IntegerColumn("xtargets")
		FirstlogonColumn            = mysql.IntegerColumn("firstlogon")
		EAaEffectsColumn            = mysql.IntegerColumn("e_aa_effects")
		EPercentToAaColumn          = mysql.IntegerColumn("e_percent_to_aa")
		EExpendedAaSpentColumn      = mysql.IntegerColumn("e_expended_aa_spent")
		AaPointsSpentOldColumn      = mysql.IntegerColumn("aa_points_spent_old")
		AaPointsOldColumn           = mysql.IntegerColumn("aa_points_old")
		ELastInvsnapshotColumn      = mysql.IntegerColumn("e_last_invsnapshot")
		DeletedAtColumn             = mysql.TimestampColumn("deleted_at")
		IllusionBlockColumn         = mysql.IntegerColumn("illusion_block")
		allColumns                  = mysql.ColumnList{IDColumn, AccountIDColumn, NameColumn, LastNameColumn, TitleColumn, SuffixColumn, ZoneIDColumn, ZoneInstanceColumn, YColumn, XColumn, ZColumn, HeadingColumn, GenderColumn, RaceColumn, ClassColumn, LevelColumn, DeityColumn, BirthdayColumn, LastLoginColumn, TimePlayedColumn, Level2Column, AnonColumn, GmColumn, FaceColumn, HairColorColumn, HairStyleColumn, BeardColumn, BeardColorColumn, EyeColor1Column, EyeColor2Column, DrakkinHeritageColumn, DrakkinTattooColumn, DrakkinDetailsColumn, AbilityTimeSecondsColumn, AbilityNumberColumn, AbilityTimeMinutesColumn, AbilityTimeHoursColumn, ExpColumn, ExpEnabledColumn, AaPointsSpentColumn, AaExpColumn, AaPointsColumn, GroupLeadershipExpColumn, RaidLeadershipExpColumn, GroupLeadershipPointsColumn, RaidLeadershipPointsColumn, PointsColumn, CurHpColumn, ManaColumn, EnduranceColumn, IntoxicationColumn, StrColumn, StaColumn, ChaColumn, DexColumn, IntColumn, AgiColumn, WisColumn, ExtraHasteColumn, ZoneChangeCountColumn, ToxicityColumn, HungerLevelColumn, ThirstLevelColumn, AbilityUpColumn, LdonPointsGukColumn, LdonPointsMirColumn, LdonPointsMmcColumn, LdonPointsRujColumn, LdonPointsTakColumn, LdonPointsAvailableColumn, TributeTimeRemainingColumn, CareerTributePointsColumn, TributePointsColumn, TributeActiveColumn, PvpStatusColumn, PvpKillsColumn, PvpDeathsColumn, PvpCurrentPointsColumn, PvpCareerPointsColumn, PvpBestKillStreakColumn, PvpWorstDeathStreakColumn, PvpCurrentKillStreakColumn, Pvp2Column, PvpTypeColumn, ShowHelmColumn, GroupAutoConsentColumn, RaidAutoConsentColumn, GuildAutoConsentColumn, LeadershipExpOnColumn, RestTimerColumn, AirRemainingColumn, AutosplitEnabledColumn, LfpColumn, LfgColumn, MailkeyColumn, XtargetsColumn, FirstlogonColumn, EAaEffectsColumn, EPercentToAaColumn, EExpendedAaSpentColumn, AaPointsSpentOldColumn, AaPointsOldColumn, ELastInvsnapshotColumn, DeletedAtColumn, IllusionBlockColumn}
		mutableColumns              = mysql.ColumnList{AccountIDColumn, NameColumn, LastNameColumn, TitleColumn, SuffixColumn, ZoneIDColumn, ZoneInstanceColumn, YColumn, XColumn, ZColumn, HeadingColumn, GenderColumn, RaceColumn, ClassColumn, LevelColumn, DeityColumn, BirthdayColumn, LastLoginColumn, TimePlayedColumn, Level2Column, AnonColumn, GmColumn, FaceColumn, HairColorColumn, HairStyleColumn, BeardColumn, BeardColorColumn, EyeColor1Column, EyeColor2Column, DrakkinHeritageColumn, DrakkinTattooColumn, DrakkinDetailsColumn, AbilityTimeSecondsColumn, AbilityNumberColumn, AbilityTimeMinutesColumn, AbilityTimeHoursColumn, ExpColumn, ExpEnabledColumn, AaPointsSpentColumn, AaExpColumn, AaPointsColumn, GroupLeadershipExpColumn, RaidLeadershipExpColumn, GroupLeadershipPointsColumn, RaidLeadershipPointsColumn, PointsColumn, CurHpColumn, ManaColumn, EnduranceColumn, IntoxicationColumn, StrColumn, StaColumn, ChaColumn, DexColumn, IntColumn, AgiColumn, WisColumn, ExtraHasteColumn, ZoneChangeCountColumn, ToxicityColumn, HungerLevelColumn, ThirstLevelColumn, AbilityUpColumn, LdonPointsGukColumn, LdonPointsMirColumn, LdonPointsMmcColumn, LdonPointsRujColumn, LdonPointsTakColumn, LdonPointsAvailableColumn, TributeTimeRemainingColumn, CareerTributePointsColumn, TributePointsColumn, TributeActiveColumn, PvpStatusColumn, PvpKillsColumn, PvpDeathsColumn, PvpCurrentPointsColumn, PvpCareerPointsColumn, PvpBestKillStreakColumn, PvpWorstDeathStreakColumn, PvpCurrentKillStreakColumn, Pvp2Column, PvpTypeColumn, ShowHelmColumn, GroupAutoConsentColumn, RaidAutoConsentColumn, GuildAutoConsentColumn, LeadershipExpOnColumn, RestTimerColumn, AirRemainingColumn, AutosplitEnabledColumn, LfpColumn, LfgColumn, MailkeyColumn, XtargetsColumn, FirstlogonColumn, EAaEffectsColumn, EPercentToAaColumn, EExpendedAaSpentColumn, AaPointsSpentOldColumn, AaPointsOldColumn, ELastInvsnapshotColumn, DeletedAtColumn, IllusionBlockColumn}
		defaultColumns              = mysql.ColumnList{AccountIDColumn, NameColumn, LastNameColumn, TitleColumn, SuffixColumn, ZoneIDColumn, ZoneInstanceColumn, YColumn, XColumn, ZColumn, HeadingColumn, GenderColumn, RaceColumn, ClassColumn, LevelColumn, DeityColumn, BirthdayColumn, LastLoginColumn, TimePlayedColumn, Level2Column, AnonColumn, GmColumn, FaceColumn, HairColorColumn, HairStyleColumn, BeardColumn, BeardColorColumn, EyeColor1Column, EyeColor2Column, DrakkinHeritageColumn, DrakkinTattooColumn, DrakkinDetailsColumn, AbilityTimeSecondsColumn, AbilityNumberColumn, AbilityTimeMinutesColumn, AbilityTimeHoursColumn, ExpColumn, ExpEnabledColumn, AaPointsSpentColumn, AaExpColumn, AaPointsColumn, GroupLeadershipExpColumn, RaidLeadershipExpColumn, GroupLeadershipPointsColumn, RaidLeadershipPointsColumn, PointsColumn, CurHpColumn, ManaColumn, EnduranceColumn, IntoxicationColumn, StrColumn, StaColumn, ChaColumn, DexColumn, IntColumn, AgiColumn, WisColumn, ExtraHasteColumn, ZoneChangeCountColumn, ToxicityColumn, HungerLevelColumn, ThirstLevelColumn, AbilityUpColumn, LdonPointsGukColumn, LdonPointsMirColumn, LdonPointsMmcColumn, LdonPointsRujColumn, LdonPointsTakColumn, LdonPointsAvailableColumn, TributeTimeRemainingColumn, CareerTributePointsColumn, TributePointsColumn, TributeActiveColumn, PvpStatusColumn, PvpKillsColumn, PvpDeathsColumn, PvpCurrentPointsColumn, PvpCareerPointsColumn, PvpBestKillStreakColumn, PvpWorstDeathStreakColumn, PvpCurrentKillStreakColumn, Pvp2Column, PvpTypeColumn, ShowHelmColumn, GroupAutoConsentColumn, RaidAutoConsentColumn, GuildAutoConsentColumn, LeadershipExpOnColumn, RestTimerColumn, AirRemainingColumn, AutosplitEnabledColumn, LfpColumn, LfgColumn, MailkeyColumn, XtargetsColumn, FirstlogonColumn, EAaEffectsColumn, EPercentToAaColumn, EExpendedAaSpentColumn, AaPointsSpentOldColumn, AaPointsOldColumn, ELastInvsnapshotColumn, IllusionBlockColumn}
	)

	return characterDataTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                    IDColumn,
		AccountID:             AccountIDColumn,
		Name:                  NameColumn,
		LastName:              LastNameColumn,
		Title:                 TitleColumn,
		Suffix:                SuffixColumn,
		ZoneID:                ZoneIDColumn,
		ZoneInstance:          ZoneInstanceColumn,
		Y:                     YColumn,
		X:                     XColumn,
		Z:                     ZColumn,
		Heading:               HeadingColumn,
		Gender:                GenderColumn,
		Race:                  RaceColumn,
		Class:                 ClassColumn,
		Level:                 LevelColumn,
		Deity:                 DeityColumn,
		Birthday:              BirthdayColumn,
		LastLogin:             LastLoginColumn,
		TimePlayed:            TimePlayedColumn,
		Level2:                Level2Column,
		Anon:                  AnonColumn,
		Gm:                    GmColumn,
		Face:                  FaceColumn,
		HairColor:             HairColorColumn,
		HairStyle:             HairStyleColumn,
		Beard:                 BeardColumn,
		BeardColor:            BeardColorColumn,
		EyeColor1:             EyeColor1Column,
		EyeColor2:             EyeColor2Column,
		DrakkinHeritage:       DrakkinHeritageColumn,
		DrakkinTattoo:         DrakkinTattooColumn,
		DrakkinDetails:        DrakkinDetailsColumn,
		AbilityTimeSeconds:    AbilityTimeSecondsColumn,
		AbilityNumber:         AbilityNumberColumn,
		AbilityTimeMinutes:    AbilityTimeMinutesColumn,
		AbilityTimeHours:      AbilityTimeHoursColumn,
		Exp:                   ExpColumn,
		ExpEnabled:            ExpEnabledColumn,
		AaPointsSpent:         AaPointsSpentColumn,
		AaExp:                 AaExpColumn,
		AaPoints:              AaPointsColumn,
		GroupLeadershipExp:    GroupLeadershipExpColumn,
		RaidLeadershipExp:     RaidLeadershipExpColumn,
		GroupLeadershipPoints: GroupLeadershipPointsColumn,
		RaidLeadershipPoints:  RaidLeadershipPointsColumn,
		Points:                PointsColumn,
		CurHp:                 CurHpColumn,
		Mana:                  ManaColumn,
		Endurance:             EnduranceColumn,
		Intoxication:          IntoxicationColumn,
		Str:                   StrColumn,
		Sta:                   StaColumn,
		Cha:                   ChaColumn,
		Dex:                   DexColumn,
		Int:                   IntColumn,
		Agi:                   AgiColumn,
		Wis:                   WisColumn,
		ExtraHaste:            ExtraHasteColumn,
		ZoneChangeCount:       ZoneChangeCountColumn,
		Toxicity:              ToxicityColumn,
		HungerLevel:           HungerLevelColumn,
		ThirstLevel:           ThirstLevelColumn,
		AbilityUp:             AbilityUpColumn,
		LdonPointsGuk:         LdonPointsGukColumn,
		LdonPointsMir:         LdonPointsMirColumn,
		LdonPointsMmc:         LdonPointsMmcColumn,
		LdonPointsRuj:         LdonPointsRujColumn,
		LdonPointsTak:         LdonPointsTakColumn,
		LdonPointsAvailable:   LdonPointsAvailableColumn,
		TributeTimeRemaining:  TributeTimeRemainingColumn,
		CareerTributePoints:   CareerTributePointsColumn,
		TributePoints:         TributePointsColumn,
		TributeActive:         TributeActiveColumn,
		PvpStatus:             PvpStatusColumn,
		PvpKills:              PvpKillsColumn,
		PvpDeaths:             PvpDeathsColumn,
		PvpCurrentPoints:      PvpCurrentPointsColumn,
		PvpCareerPoints:       PvpCareerPointsColumn,
		PvpBestKillStreak:     PvpBestKillStreakColumn,
		PvpWorstDeathStreak:   PvpWorstDeathStreakColumn,
		PvpCurrentKillStreak:  PvpCurrentKillStreakColumn,
		Pvp2:                  Pvp2Column,
		PvpType:               PvpTypeColumn,
		ShowHelm:              ShowHelmColumn,
		GroupAutoConsent:      GroupAutoConsentColumn,
		RaidAutoConsent:       RaidAutoConsentColumn,
		GuildAutoConsent:      GuildAutoConsentColumn,
		LeadershipExpOn:       LeadershipExpOnColumn,
		RestTimer:             RestTimerColumn,
		AirRemaining:          AirRemainingColumn,
		AutosplitEnabled:      AutosplitEnabledColumn,
		Lfp:                   LfpColumn,
		Lfg:                   LfgColumn,
		Mailkey:               MailkeyColumn,
		Xtargets:              XtargetsColumn,
		Firstlogon:            FirstlogonColumn,
		EAaEffects:            EAaEffectsColumn,
		EPercentToAa:          EPercentToAaColumn,
		EExpendedAaSpent:      EExpendedAaSpentColumn,
		AaPointsSpentOld:      AaPointsSpentOldColumn,
		AaPointsOld:           AaPointsOldColumn,
		ELastInvsnapshot:      ELastInvsnapshotColumn,
		DeletedAt:             DeletedAtColumn,
		IllusionBlock:         IllusionBlockColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
