//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var QsPlayerEvents = newQsPlayerEventsTable("eqgo", "qs_player_events", "")

type qsPlayerEventsTable struct {
	mysql.Table

	// Columns
	ID        mysql.ColumnInteger
	CharID    mysql.ColumnInteger
	Event     mysql.ColumnInteger
	EventDesc mysql.ColumnString
	Time      mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type QsPlayerEventsTable struct {
	qsPlayerEventsTable

	NEW qsPlayerEventsTable
}

// AS creates new QsPlayerEventsTable with assigned alias
func (a QsPlayerEventsTable) AS(alias string) *QsPlayerEventsTable {
	return newQsPlayerEventsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new QsPlayerEventsTable with assigned schema name
func (a QsPlayerEventsTable) FromSchema(schemaName string) *QsPlayerEventsTable {
	return newQsPlayerEventsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new QsPlayerEventsTable with assigned table prefix
func (a QsPlayerEventsTable) WithPrefix(prefix string) *QsPlayerEventsTable {
	return newQsPlayerEventsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new QsPlayerEventsTable with assigned table suffix
func (a QsPlayerEventsTable) WithSuffix(suffix string) *QsPlayerEventsTable {
	return newQsPlayerEventsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newQsPlayerEventsTable(schemaName, tableName, alias string) *QsPlayerEventsTable {
	return &QsPlayerEventsTable{
		qsPlayerEventsTable: newQsPlayerEventsTableImpl(schemaName, tableName, alias),
		NEW:                 newQsPlayerEventsTableImpl("", "new", ""),
	}
}

func newQsPlayerEventsTableImpl(schemaName, tableName, alias string) qsPlayerEventsTable {
	var (
		IDColumn        = mysql.IntegerColumn("id")
		CharIDColumn    = mysql.IntegerColumn("char_id")
		EventColumn     = mysql.IntegerColumn("event")
		EventDescColumn = mysql.StringColumn("event_desc")
		TimeColumn      = mysql.IntegerColumn("time")
		allColumns      = mysql.ColumnList{IDColumn, CharIDColumn, EventColumn, EventDescColumn, TimeColumn}
		mutableColumns  = mysql.ColumnList{CharIDColumn, EventColumn, EventDescColumn, TimeColumn}
		defaultColumns  = mysql.ColumnList{CharIDColumn, EventColumn, TimeColumn}
	)

	return qsPlayerEventsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		CharID:    CharIDColumn,
		Event:     EventColumn,
		EventDesc: EventDescColumn,
		Time:      TimeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
