//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Races = newRacesTable("eqgo", "races", "")

type racesTable struct {
	mysql.Table

	// Columns
	ID         mysql.ColumnInteger
	Name       mysql.ColumnString
	ShortName  mysql.ColumnString
	Bitmask    mysql.ColumnInteger
	NoCoin     mysql.ColumnInteger
	IsPlayable mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type RacesTable struct {
	racesTable

	NEW racesTable
}

// AS creates new RacesTable with assigned alias
func (a RacesTable) AS(alias string) *RacesTable {
	return newRacesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RacesTable with assigned schema name
func (a RacesTable) FromSchema(schemaName string) *RacesTable {
	return newRacesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RacesTable with assigned table prefix
func (a RacesTable) WithPrefix(prefix string) *RacesTable {
	return newRacesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RacesTable with assigned table suffix
func (a RacesTable) WithSuffix(suffix string) *RacesTable {
	return newRacesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRacesTable(schemaName, tableName, alias string) *RacesTable {
	return &RacesTable{
		racesTable: newRacesTableImpl(schemaName, tableName, alias),
		NEW:        newRacesTableImpl("", "new", ""),
	}
}

func newRacesTableImpl(schemaName, tableName, alias string) racesTable {
	var (
		IDColumn         = mysql.IntegerColumn("id")
		NameColumn       = mysql.StringColumn("name")
		ShortNameColumn  = mysql.StringColumn("short_name")
		BitmaskColumn    = mysql.IntegerColumn("bitmask")
		NoCoinColumn     = mysql.IntegerColumn("no_coin")
		IsPlayableColumn = mysql.IntegerColumn("is_playable")
		allColumns       = mysql.ColumnList{IDColumn, NameColumn, ShortNameColumn, BitmaskColumn, NoCoinColumn, IsPlayableColumn}
		mutableColumns   = mysql.ColumnList{NameColumn, ShortNameColumn, BitmaskColumn, NoCoinColumn, IsPlayableColumn}
		defaultColumns   = mysql.ColumnList{NoCoinColumn, IsPlayableColumn}
	)

	return racesTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		Name:       NameColumn,
		ShortName:  ShortNameColumn,
		Bitmask:    BitmaskColumn,
		NoCoin:     NoCoinColumn,
		IsPlayable: IsPlayableColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
