//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var SpireUserEventLog = newSpireUserEventLogTable("eqgo", "spire_user_event_log", "")

type spireUserEventLogTable struct {
	mysql.Table

	// Columns
	ID                         mysql.ColumnInteger
	UserID                     mysql.ColumnInteger
	ServerDatabaseConnectionID mysql.ColumnInteger
	EventName                  mysql.ColumnString
	Data                       mysql.ColumnString
	CreatedAt                  mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type SpireUserEventLogTable struct {
	spireUserEventLogTable

	NEW spireUserEventLogTable
}

// AS creates new SpireUserEventLogTable with assigned alias
func (a SpireUserEventLogTable) AS(alias string) *SpireUserEventLogTable {
	return newSpireUserEventLogTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SpireUserEventLogTable with assigned schema name
func (a SpireUserEventLogTable) FromSchema(schemaName string) *SpireUserEventLogTable {
	return newSpireUserEventLogTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SpireUserEventLogTable with assigned table prefix
func (a SpireUserEventLogTable) WithPrefix(prefix string) *SpireUserEventLogTable {
	return newSpireUserEventLogTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SpireUserEventLogTable with assigned table suffix
func (a SpireUserEventLogTable) WithSuffix(suffix string) *SpireUserEventLogTable {
	return newSpireUserEventLogTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSpireUserEventLogTable(schemaName, tableName, alias string) *SpireUserEventLogTable {
	return &SpireUserEventLogTable{
		spireUserEventLogTable: newSpireUserEventLogTableImpl(schemaName, tableName, alias),
		NEW:                    newSpireUserEventLogTableImpl("", "new", ""),
	}
}

func newSpireUserEventLogTableImpl(schemaName, tableName, alias string) spireUserEventLogTable {
	var (
		IDColumn                         = mysql.IntegerColumn("id")
		UserIDColumn                     = mysql.IntegerColumn("user_id")
		ServerDatabaseConnectionIDColumn = mysql.IntegerColumn("server_database_connection_id")
		EventNameColumn                  = mysql.StringColumn("event_name")
		DataColumn                       = mysql.StringColumn("data")
		CreatedAtColumn                  = mysql.TimestampColumn("created_at")
		allColumns                       = mysql.ColumnList{IDColumn, UserIDColumn, ServerDatabaseConnectionIDColumn, EventNameColumn, DataColumn, CreatedAtColumn}
		mutableColumns                   = mysql.ColumnList{UserIDColumn, ServerDatabaseConnectionIDColumn, EventNameColumn, DataColumn, CreatedAtColumn}
		defaultColumns                   = mysql.ColumnList{}
	)

	return spireUserEventLogTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                         IDColumn,
		UserID:                     UserIDColumn,
		ServerDatabaseConnectionID: ServerDatabaseConnectionIDColumn,
		EventName:                  EventNameColumn,
		Data:                       DataColumn,
		CreatedAt:                  CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
