/* eslint-disable @typescript-eslint/no-unused-vars */
// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = BigInt("0xd12a1c51fedd6c88");
