/* eslint-disable @typescript-eslint/no-unused-vars */
// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = BigInt("0x9a7b8c6d5e4f3210");
export class JWTLogin extends $.Struct {
  static readonly _capnp = {
    displayName: "JWTLogin",
    id: "9b02ee5625ec21fb",
    size: new $.ObjectSize(0, 1)
  };
  get token(): string {
    return $.utils.getText(0, this);
  }
  set token(value: string) {
    $.utils.setText(0, value, this);
  }
  toString(): string {
    return "JWTLogin_" + super.toString();
  }
}
export class JWTResponse extends $.Struct {
  static readonly _capnp = {
    displayName: "JWTResponse",
    id: "8a5026d84a4c9312",
    size: new $.ObjectSize(8, 0)
  };
  get status(): number {
    return $.utils.getInt32(0, this);
  }
  set status(value: number) {
    $.utils.setInt32(0, value, this);
  }
  toString(): string {
    return "JWTResponse_" + super.toString();
  }
}
export class WebInitiateConnection extends $.Struct {
  static readonly _capnp = {
    displayName: "WebInitiateConnection",
    id: "e72e2063d179e57d",
    size: new $.ObjectSize(8, 0)
  };
  get login(): boolean {
    return $.utils.getBit(0, this);
  }
  set login(value: boolean) {
    $.utils.setBit(0, value, this);
  }
  toString(): string {
    return "WebInitiateConnection_" + super.toString();
  }
}
export class EnterWorld extends $.Struct {
  static readonly _capnp = {
    displayName: "EnterWorld",
    id: "df0c1226c90e00ad",
    size: new $.ObjectSize(8, 1)
  };
  get name(): string {
    return $.utils.getText(0, this);
  }
  set name(value: string) {
    $.utils.setText(0, value, this);
  }
  get tutorial(): number {
    return $.utils.getInt32(0, this);
  }
  set tutorial(value: number) {
    $.utils.setInt32(0, value, this);
  }
  get returnHome(): number {
    return $.utils.getInt32(4, this);
  }
  set returnHome(value: number) {
    $.utils.setInt32(4, value, this);
  }
  toString(): string {
    return "EnterWorld_" + super.toString();
  }
}
export class NameApproval extends $.Struct {
  static readonly _capnp = {
    displayName: "NameApproval",
    id: "fe88232d771013d6",
    size: new $.ObjectSize(16, 1)
  };
  get name(): string {
    return $.utils.getText(0, this);
  }
  set name(value: string) {
    $.utils.setText(0, value, this);
  }
  get race(): number {
    return $.utils.getInt32(0, this);
  }
  set race(value: number) {
    $.utils.setInt32(0, value, this);
  }
  get charClass(): number {
    return $.utils.getInt32(4, this);
  }
  set charClass(value: number) {
    $.utils.setInt32(4, value, this);
  }
  get deity(): number {
    return $.utils.getInt32(8, this);
  }
  set deity(value: number) {
    $.utils.setInt32(8, value, this);
  }
  toString(): string {
    return "NameApproval_" + super.toString();
  }
}
