//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type CharacterExpeditionLockouts struct {
	ID                 uint32 `sql:"primary_key"`
	CharacterID        uint32
	ExpeditionName     string
	EventName          string
	ExpireTime         time.Time
	Duration           uint32
	FromExpeditionUUID string
}
