//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type CharacterBuffs struct {
	CharacterID   uint32 `sql:"primary_key"`
	SlotID        uint8  `sql:"primary_key"`
	SpellID       uint16
	CasterLevel   uint8
	CasterName    string
	Ticsremaining int32
	Counters      uint32
	Numhits       uint32
	MeleeRune     uint32
	MagicRune     uint32
	Persistent    uint8
	DotRune       int32
	CastonX       int32
	CastonY       int32
	CastonZ       int32
	ExtraDIChance int32
	InstrumentMod int32
}
