//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type CharacterPetInfo struct {
	CharID   int32 `sql:"primary_key"`
	Pet      int32 `sql:"primary_key"`
	Petname  string
	Petpower int32
	SpellID  int32
	Hp       int32
	Mana     int32
	Size     float64
	Taunting bool
}
