//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type DiscoveredItems struct {
	ItemID         uint32 `sql:"primary_key"`
	CharName       string
	DiscoveredDate uint32
	AccountStatus  int32
}
