//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type DynamicZoneTemplates struct {
	ID              uint32 `sql:"primary_key"`
	ZoneID          int32
	ZoneVersion     int32
	Name            string
	MinPlayers      int32
	MaxPlayers      int32
	DurationSeconds int32
	DzSwitchID      int32
	CompassZoneID   int32
	CompassX        float64
	CompassY        float64
	CompassZ        float64
	ReturnZoneID    int32
	ReturnX         float64
	ReturnY         float64
	ReturnZ         float64
	ReturnH         float64
	OverrideZoneIn  int8
	ZoneInX         float64
	ZoneInY         float64
	ZoneInZ         float64
	ZoneInH         float64
}
