//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Forage struct {
	ID                   int32 `sql:"primary_key"`
	Zoneid               int32
	Itemid               int32
	Level                int16
	Chance               int16
	MinExpansion         int8
	MaxExpansion         int8
	ContentFlags         *string
	ContentFlagsDisabled *string
}
