//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Graveyard struct {
	ID      int32 `sql:"primary_key"`
	ZoneID  int32
	X       float64
	Y       float64
	Z       float64
	Heading float64
}
