//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type GuildBank struct {
	ID             uint32 `sql:"primary_key"`
	GuildID        uint32
	Area           uint8
	Slot           uint32
	ItemID         uint32
	AugmentOneID   *uint32
	AugmentTwoID   *uint32
	AugmentThreeID *uint32
	AugmentFourID  *uint32
	AugmentFiveID  *uint32
	AugmentSixID   *uint32
	Quantity       int32
	Donator        *string
	Permissions    uint8
	WhoFor         *string
}
