//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type PlayerEventNpcHandin struct {
	ID             uint64 `sql:"primary_key"`
	NpcID          *uint32
	NpcName        *string
	HandinCopper   *uint64
	HandinSilver   *uint64
	HandinGold     *uint64
	HandinPlatinum *uint64
	ReturnCopper   *uint64
	ReturnSilver   *uint64
	ReturnGold     *uint64
	ReturnPlatinum *uint64
	IsQuestHandin  *uint8
	CreatedAt      *time.Time
}
