//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type RuleValues struct {
	RulesetID uint8  `sql:"primary_key"`
	RuleName  string `sql:"primary_key"`
	RuleValue string
	Notes     *string
}
