package opcodes

type OpCode uint16

const (
	Reconnect OpCode = iota
	Padding1
	Padding2
	//////////////////////
	// Handled OP Codes //
	//////////////////////

	// JWT
	JWTResponse
	JWTLogin

	// Login
	LoginAccepted
	PlayEverquestRequest
	PlayEverquestResponse
	ServerListRequest
	ServerListResponse

	// World
	ApproveName
	CharacterCreate
	DeleteCharacter
	ApproveName_Server
	EnterWorld
	ExpansionInfo
	GuildsList
	PostEnterWorld
	SendCharInfo
	SendLoginInfo
	SendMaxCharacters
	SendMembership
	SendMembershipDetails
	ZoneServerInfo
	WebInitiateConnection

	// Zone
	ZoneSession
	ZoneSessionValid
	ZoneEntry
	SetServerFilter
	SendAATable
	SendTributes
	SendGuildTributes
	SendAAStats
	ReqClientSpawn
	ReqNewZone
	SendExpZonein
	ClientReady
	ClientError
	ApproveZone
	TGB
	AckPacket
	ClientUpdate
	AutoAttack
	AutoAttack2
	Consent
	ConsentDeny
	TargetMouse
	TargetCommand
	Shielding
	Jump
	AdventureInfoRequest
	AdventureRequest
	LDoNButton
	LeaveAdventure
	Consume
	AdventureMerchantRequest
	AdventureMerchantPurchase
	ConsiderCorpse
	Consider
	Begging
	TestBuff
	Surname
	YellForHelp
	Assist
	GMTraining
	GMEndTraining
	GMTrainSkill
	RequestDuel
	DuelDecline
	DuelAccept
	SpawnAppearance
	BazaarInspect
	Death
	MoveCoin
	ItemLinkClick
	MoveItem
	Camp
	Logout
	SenseHeading
	FeignDeath
	Sneak
	Hide
	ChannelMessage
	GMCommand
	WearChange
	DeleteSpawn
	SaveOnZoneReq
	Save
	WhoAllRequest
	GMZoneRequest
	GMZoneRequest2
	EndLootRequest
	LootRequest
	Dye
	ConfirmDelete
	LootItem
	GuildDelete
	GuildPublicNote
	GetGuildsList
	SetGuildMOTD
	SetRunMode
	GuildPeace
	GuildWar
	GuildLeader
	GuildDemote
	GuildInvite
	GuildRemove
	GuildInviteAccept
	ManaChange
	MemorizeSpell
	SwapSpell
	CastSpell
	DeleteItem
	DeleteItems
	CombatAbility
	Taunt
	InstillDoubt
	RezzAnswer
	GMSummon
	TradeBusy
	TradeRequest
	TradeRequestAck
	CancelTrade
	TradeAcceptClick
	BoardBoat
	LeaveBoat
	RandomReq
	Buff
	GMHideMe
	GMNameChange
	GMKill
	GMLastName
	GMToggle
	LFGCommand
	GMGoto
	TraderShop
	ShopRequest
	Bazaar
	ShopPlayerBuy
	ShopPlayerSell
	ShopEnd
	CloseContainer
	ClickObjectAction
	ClickObject
	RecipesFavorite
	RecipesSearch
	RecipeDetails
	RecipeAutoCombine
	TradeSkillCombine
	ItemName
	AugmentItem
	ClickDoor
	FaceChange
	GroupInvite
	GroupInvite2
	GroupFollow
	GroupFollow2
	GroupAcknowledge
	GroupCancelInvite
	GroupDisband
	GroupDelete
	GMEmoteZone
	InspectRequest
	InspectAnswer
	DeleteSpell
	PetitionBug
	Bug
	Petition
	PetitionCheckIn
	PetitionResolve
	PetitionDelete
	PetitionUnCheckout
	PetitionQue
	PDeletePetition
	PetitionCheckout
	PetitionRefresh
	PetCommands
	ReadBook
	Emote
	GMDelCorpse
	GMKick
	GMServers
	Illusion
	GMBecomeNPC
	Fishing
	Forage
	Mend
	EnvDamage
	Damage
	AAAction
	TraderBuy
	Trader
	GMFind
	PickPocket
	Bind_Wound
	TrackTarget
	Track
	TrackUnknown
	ReloadUI
	Split
	SenseTraps
	DisarmTraps
	OpenTributeMaster
	OpenGuildTributeMaster
	TributeItem
	TributeMoney
	SelectTribute
	TributeUpdate
	TributeToggle
	TributeNPC
	CrashDump
	ControlBoat
	DumpName
	SafeFallSuccess
	Heartbeat
	SafePoint
	FindPersonRequest
	LeadershipExpToggle
	PurchaseLeadershipAA
	BankerChange
	SetTitle
	RequestTitles
	ItemVerifyRequest
	ClearObject
	FinishTrade
	GMEndTrainingResponse
	LootComplete
	WorldObjectsSent
	FinishWindow
	FinishWindow2
	ItemPacket
	AddItemPacket
	ColoredText
	ItemRecastDelay
	FormattedMessage
	GuildMemberList
	InterruptCast
	ItemLinkResponse
	ZoneSpawns
	BatchZoneSpawns
	CompletedTasks
	CharInventory
	CustomTitles
	SpawnDoor
	SendZonepoints
	TributeInfo
	GuildTributeInfo
	SendTitleList
	AAExpUpdate
	Action
	AdventureData
	AdventureFinish
	AdventurePointsUpdate
	Animation
	AnnoyingZoneUnknown
	BecomeTrader
	BeginCast
	Charm
	CameraEffect
	ConsentResponse
	EnduranceUpdate
	ExpUpdate
	GroundSpawn
	GroupUpdate
	GuildMOTD
	GuildManageAdd
	GuildManageRemove
	GuildManageStatus
	GuildMemberUpdate
	HPUpdate
	IncreaseStats
	ItemVerifyReply
	LFGAppearance
	LeadershipExpUpdate
	LevelAppearance
	LevelUpdate
	ManaUpdate
	MobEnduranceUpdate
	MobHealth
	MobManaUpdate
	MobRename
	MoneyOnCorpse
	MoneyUpdate
	MoveDoor
	NewSpawn
	NewZone
	PetitionUpdate
	PlayerProfile
	RaidUpdate
	RandomReply
	RecipeReply
	RequestClientZoneChange
	RespondAA
	RezzRequest
	SetTitleReply
	ShopDelItem
	SimpleMessage
	SkillUpdate
	SomeItemPacketMaybe
	SpellEffect
	Stamina
	Stun
	TargetReject
	TimeOfDay
	TradeCoins
	TradeMoneyUpdate
	TraderDelItem
	TraderItemUpdate
	TributeTimer
	UpdateLeadershipAA
	Weather
	ZoneChange
	ZoneInUnknown
	AcceptNewTask
	AdventureInfo
	ApplyPoison
	ApproveWorld
	Bandolier
	BazaarSearch
	BecomeCorpse
	CancelTask
	Command
	DynamicWall
	LFGuild
	LoadSpellSet
	LogServer
	MOTD
	OnLevelMessage
	PlayMP3
	PotionBelt
	PVPStats
	Report
	SpecialMesg
	TaskActivity
	TaskDescription
	ZoneUnavail
	ExploreUnknown
	Action2
	AddNimbusEffect
	AdventureDetails
	AdventureLeaderboardReply
	AdventureLeaderboardRequest
	AdventureMerchantResponse
	AdventureMerchantSell
	AdventureStatsReply
	AdventureStatsRequest
	AdventureUpdate
	AggroMeterLockTarget
	AggroMeterTargetInfo
	AggroMeterUpdate
	AltCurrency
	AltCurrencyMerchantReply
	AltCurrencyMerchantRequest
	AltCurrencyPurchase
	AltCurrencyReclaim
	AltCurrencySell
	AltCurrencySellSelection
	AssistGroup
	AugmentInfo
	AutoFire
	Barter
	BlockedBuffs
	BookButton
	BuffCreate
	BuffRemoveRequest
	CancelSneakHide
	CashReward
	ChangeSize
	CharacterCreateRequest
	ChatMessage
	ClearAA
	ClearBlockedBuffs
	ClearLeadershipAbilities
	ClearNPCMarks
	ClearSurname
	ClientTimeStamp
	CloseTributeMaster
	CorpseDrag
	CorpseDrop
	CrystalCountUpdate
	CrystalCreate
	CrystalReclaim
	DelegateAbility
	DeleteCharge
	DeletePetition
	DenyResponse
	Disarm
	DisciplineTimer
	DisciplineUpdate
	DiscordMerchantInventory
	DoGroupLeadershipAbility
	DzAddPlayer
	DzChooseZone
	DzChooseZoneReply
	DzCompass
	DzExpeditionEndsWarning
	DzExpeditionInfo
	DzExpeditionInvite
	DzExpeditionInviteResponse
	DzExpeditionLockoutTimers
	DzListTimers
	DzMakeLeader
	DzMemberList
	DzMemberListName
	DzMemberListStatus
	DzPlayerList
	DzQuit
	DzRemovePlayer
	DzSetLeaderName
	DzSwapPlayer
	EnterChat
	Feedback
	FellowshipUpdate
	FindPersonReply
	Fling
	FloatListThing
	ForceFindPerson
	FriendsWho
	GetGuildMOTD
	GetGuildMOTDReply
	GiveMoney
	GMApproval
	GMTrainSkillConfirm
	GroupDisbandOther
	GroupDisbandYou
	GroupLeaderChange
	GroupLeadershipAAUpdate
	GroupMakeLeader
	GroupMentor
	GroupRoles
	GroupUpdateB
	GroupUpdateLeaderAA
	GuildBank
	GuildBankItemList
	GuildCreate
	GuildManageBanker
	GuildMemberLevelUpdate
	GuildPromote
	GuildStatus
	GuildUpdateURLAndChannel
	HideCorpse
	InitialHPUpdate
	InitialMobHealth
	InspectBuffs
	InspectMessageUpdate
	ItemLinkText
	ItemPreview
	ItemViewUnknown
	KeyRing
	KickPlayers
	KnowledgeBase
	LDoNDisarmTraps
	LDoNInspect
	LDoNOpen
	LDoNPickLock
	LDoNSenseTraps
	LFGGetMatchesRequest
	LFGGetMatchesResponse
	LFGResponse
	LFPCommand
	LFPGetMatchesRequest
	LFPGetMatchesResponse
	LinkedReuse
	LocInfo
	LockoutTimerInfo
	Login
	LoginComplete
	LoginExpansionPacketData
	LoginUnknown1
	LoginUnknown2
	LogoutReply
	MarkNPC
	MarkRaidNPC
	Marquee
	MendHPUpdate
	MercenaryAssign
	MercenaryCommand
	MercenaryDataRequest
	MercenaryDataResponse
	MercenaryDataUpdate
	MercenaryDataUpdateRequest
	MercenaryDismiss
	MercenaryHire
	MercenarySuspendRequest
	MercenarySuspendResponse
	MercenaryTimer
	MercenaryTimerRequest
	MercenaryUnknown1
	MercenaryUnsuspendResponse
	MobUpdate
	MoveMultipleItems
	MoveLogDisregard
	MoveLogRequest
	MultiLineMsg
	NewTitlesAvailable
	OpenContainer
	OpenDiscordMerchant
	OpenInventory
	PetBuffWindow
	PetCommandState
	PetHoTT
	PetitionCheckout2
	PetitionSearch
	PetitionSearchResults
	PetitionSearchText
	PlayerStateAdd
	PlayerStateRemove
	Poll
	PollResponse
	PopupResponse
	PreLogoutReply
	PVPLeaderBoardDetailsReply
	PVPLeaderBoardDetailsRequest
	PVPLeaderBoardReply
	PVPLeaderBoardRequest
	QueryResponseThing
	QueryUCSServerStatus
	RaidDelegateAbility
	RaidClearNPCMarks
	RaidInvite
	RaidJoin
	RandomNameGenerator
	ReclaimCrystals
	RemoveAllDoors
	RemoveBlockedBuffs
	RemoveNimbusEffect
	RemoveTrap
	RequestKnowledgeBase
	RespawnWindow
	RestState
	Rewind
	RezzComplete
	Sacrifice
	SendFindableNPCs
	SendSystemStats
	SessionReady
	SetChatServer
	SetChatServer2
	SetFace
	SetGroupTarget
	SetGuildRank
	SetStartCity
	SharedTaskMemberList
	SharedTaskAddPlayer
	SharedTaskRemovePlayer
	SharedTaskMakeLeader
	SharedTaskMemberInvite
	SharedTaskInvite
	SharedTaskInviteResponse
	SharedTaskAcceptNew
	SharedTaskMemberChange
	SharedTaskPlayerList
	SharedTaskSelectWindow
	SharedTaskQuit
	TaskTimers
	ShopEndConfirm
	ShopItem
	Some3ByteHPUpdate
	Some6ByteHPUpdate
	Sound
	SpawnPositionUpdate
	TargetBuffs
	TargetHoTT
	TaskActivityComplete
	TaskHistoryReply
	TaskHistoryRequest
	TaskRequestTimer
	TaskSelectWindow
	Translocate
	TributePointUpdate
	Untargetable
	UpdateAA
	UpdateAura
	VetClaimReply
	VetClaimRequest
	VetRewardsAvaliable
	VoiceMacroIn
	VoiceMacroOut
	WeaponEquip1
	Weblink
	WhoAllResponse
	World_Client_CRC1
	World_Client_CRC2
	World_Client_CRC3
	WorldClientReady
	WorldComplete
	WorldLogout
	WorldUnknown001
	XTargetAutoAddHaters
	XTargetOpen
	XTargetOpenResponse
	XTargetRequest
	XTargetResponse
	ZoneComplete
	ZoneGuildList
	ZonePlayerToBind
	ZoneServerReady
	ResetAA
	UnderWorld
)
