import { InventoryItem } from "./InventoryItem";
import { CharacterAttributes } from "./CharacterAttributes";
import { CharacterStats } from "./CharacterStats";
import Zone from "./Zone";
import CharacterClass from "./CharacterClass";
import Race from "./Race";
import Deity from "./Deity";

export default interface CharacterProfile {
  id?: number;
  accountId?: number;
  forumId?: number;
  name?: string;
  lastName?: string;
  title?: string;
  suffix?: string;
  zoneId?: number;
  position?: {
    x?: number;
    y?: number;
    z?: number;
    heading?: number;
  };
  gender?: number;
  weightAllowance?: number;
  race?: Race;
  class?: CharacterClass;
  level?: number;
  deity?: Deity;
  birthday?: number;
  lastLogin?: number;
  timePlayed?: number;
  level2?: number;
  anon?: number;
  gm?: number;
  appearance?: {
    face?: number;
    hairColor?: number;
    hairStyle?: number;
    beard?: number;
    beardColor?: number;
    eyeColor1?: number;
    eyeColor2?: number;
  };

  exp?: number;
  aaPointsSpent?: number;
  aaExp?: number;
  aaPoints?: number;
  points?: number;
  curHp?: number;
  maxHp?: number;
  curMana?: number;
  maxMana?: number;
  endurance?: number;
  intoxication?: number;
  stats?: CharacterStats;
  attributes: CharacterAttributes;
  totalAttributes: CharacterAttributes;
  zoneChangeCount?: number;
  hungerLevel?: number;
  thirstLevel?: number;
  pvpStatus?: number;
  airRemaining?: number;
  autosplitEnabled?: number;
  mailkey?: string;
  firstLogon?: number;
  eAaEffects?: number;
  ePercentToAa?: number;
  eExpendedAaSpent?: number;
  boatId?: number;
  boatName?: string | null;
  famished?: number;
  isDeleted?: number;
  showHelm?: number;
  fatigue?: number;
  inventory?: InventoryItem[];
  startingZone?: Zone;
  platinum?: number;
  gold?: number;
  silver?: number;
  copper?: number;
  weight?: number;
}
