export enum ItemType {
  OneHandSlashing = 0,
  TwoHandSlashing = 1,
  OneHandPiercing = 2,
  OneHandBlunt = 3,
  TwoHandBlunt = 4,
  Archery = 5,
  Throwing = 7,
  Shield = 8,
  Armor = 10,
  TradeskillItems = 11,
  Lockpicking = 12,
  Food = 14,
  Drink = 15,
  LightSource = 16,
  CommonInventoryItem = 17,
  BindWound = 18,
  ThrownCastingItems = 19,
  SpellsSongSheets = 20,
  Potions = 21,
  FletchedArrows = 22,
  WindInstruments = 23,
  StringedInstruments = 24,
  BrassInstruments = 25,
  PercussionInstruments = 26,
  Ammo = 27,
  Jewelry = 29,
  ReadableNotesAndScrolls = 31,
  ReadableBooks = 32,
  Keys = 33,
  OddItems = 34,
  TwoHandPiercing = 35,
  FishingPoles = 36,
  FishingBait = 37,
  AlcoholicBeverages = 38,
  MoreKeys = 39,
  Compasses = 40,
  Poisons = 42,
  HandToHand = 45,
  Charms = 52,
  Dyes = 53,
  Augments = 54,
  AugmentSolvents = 55,
  AugmentDistillers = 56,
  FellowshipBannerMaterials = 58,
  CulturalArmorManuals = 60,
  NewCurrencies = 63,
}

export function getItemTypeName(type: ItemType): string {
  const names: Record<ItemType, string> = {
    [ItemType.OneHandSlashing]: "1H Slashing",
    [ItemType.TwoHandSlashing]: "2H Slashing",
    [ItemType.OneHandPiercing]: "1H Piercing",
    [ItemType.OneHandBlunt]: "1H Blunt",
    [ItemType.TwoHandBlunt]: "2H Blunt",
    [ItemType.Archery]: "Archery",
    [ItemType.Throwing]: "Throwing",
    [ItemType.Shield]: "Shield",
    [ItemType.Armor]: "Armor",
    [ItemType.TradeskillItems]: "Tradeskill Items",
    [ItemType.Lockpicking]: "Lockpicking",
    [ItemType.Food]: "Food",
    [ItemType.Drink]: "Drink",
    [ItemType.LightSource]: "Light Source",
    [ItemType.CommonInventoryItem]: "Common Inventory Item",
    [ItemType.BindWound]: "Bind Wound",
    [ItemType.ThrownCastingItems]: "Thrown Casting Items",
    [ItemType.SpellsSongSheets]: "Spells / Song Sheets",
    [ItemType.Potions]: "Potions",
    [ItemType.FletchedArrows]: "Fletched Arrows",
    [ItemType.WindInstruments]: "Wind Instruments",
    [ItemType.StringedInstruments]: "Stringed Instruments",
    [ItemType.BrassInstruments]: "Brass Instruments",
    [ItemType.PercussionInstruments]: "Percussion Instruments",
    [ItemType.Ammo]: "Ammo",
    [ItemType.Jewelry]: "Jewelry",
    [ItemType.ReadableNotesAndScrolls]: "Readable Notes and Scrolls",
    [ItemType.ReadableBooks]: "Readable Books",
    [ItemType.Keys]: "Keys",
    [ItemType.OddItems]: "Odd Items",
    [ItemType.TwoHandPiercing]: "2H Piercing",
    [ItemType.FishingPoles]: "Fishing Poles",
    [ItemType.FishingBait]: "Fishing Bait",
    [ItemType.AlcoholicBeverages]: "Alcoholic Beverages",
    [ItemType.MoreKeys]: "More Keys",
    [ItemType.Compasses]: "Compasses",
    [ItemType.Poisons]: "Poisons",
    [ItemType.HandToHand]: "Hand to Hand",
    [ItemType.Charms]: "Charms",
    [ItemType.Dyes]: "Dyes",
    [ItemType.Augments]: "Augments",
    [ItemType.AugmentSolvents]: "Augment Solvents",
    [ItemType.AugmentDistillers]: "Augment Distillers",
    [ItemType.FellowshipBannerMaterials]: "Fellowship Banner Materials",
    [ItemType.CulturalArmorManuals]: "Cultural Armor Manuals",
    [ItemType.NewCurrencies]: "New Currencies like Orum",
  };

  return names[type] || "Unknown";
}
