export enum Skill {
  OneHBlunt = 0,
  OneHSlashing = 1,
  TwoHBlunt = 2,
  TwoHSlashing = 3,
  Abjuration = 4,
  Alteration = 5,
  ApplyPoison = 6,
  Archery = 7,
  Backstab = 8,
  BindWound = 9,
  Bash = 10,
  Block = 11,
  BrassInstruments = 12,
  Channeling = 13,
  Conjuration = 14,
  Defense = 15,
  Disarm = 16,
  DisarmTraps = 17,
  Divination = 18,
  Dodge = 19,
  DoubleAttack = 20,
  DragonPunch = 21,
  DualWield = 22,
  EagleStrike = 23,
  Evocation = 24,
  FeignDeath = 25,
  FlyingKick = 26,
  Forage = 27,
  HandToHand = 28,
  Hide = 29,
  Kick = 30,
  Meditate = 31,
  Mend = 32,
  Offense = 33,
  Parry = 34,
  PickLock = 35,
  OneHPiercing = 36,
  Riposte = 37,
  RoundKick = 38,
  SafeFall = 39,
  SenseHeading = 40,
  Singing = 41,
  Sneak = 42,
  SpecializeAbjure = 43,
  SpecializeAlteration = 44,
  SpecializeConjuration = 45,
  SpecializeDivination = 46,
  SpecializeEvocation = 47,
  PickPockets = 48,
  StringedInstruments = 49,
  Swimming = 50,
  Throwing = 51,
  TigerClaw = 52,
  Tracking = 53,
  WindInstruments = 54,
  Fishing = 55,
  MakePoison = 56,
  Tinkering = 57,
  Research = 58,
  Alchemy = 59,
  Baking = 60,
  Tailoring = 61,
  SenseTraps = 62,
  Blacksmithing = 63,
  Fletching = 64,
  Brewing = 65,
  AlcoholTolerance = 66,
  Begging = 67,
  JewelryMaking = 68,
  Pottery = 69,
  PercussionInstruments = 70,
  Intimidation = 71,
  Berserking = 72,
  Taunt = 73,
  Frenzy = 74,
  RemoveTrap = 75,
  TripleAttack = 76,
  TwoHPiercing = 77,
}

export function getSkillName(skill: Skill): string {
  const names: Record<Skill, string> = {
    [Skill.OneHBlunt]: "1H Blunt",
    [Skill.OneHSlashing]: "1H Slashing",
    [Skill.TwoHBlunt]: "2H Blunt",
    [Skill.TwoHSlashing]: "2H Slashing",
    [Skill.Abjuration]: "Abjuration",
    [Skill.Alteration]: "Alteration",
    [Skill.ApplyPoison]: "Apply Poison",
    [Skill.Archery]: "Archery",
    [Skill.Backstab]: "Backstab",
    [Skill.BindWound]: "Bind Wound",
    [Skill.Bash]: "Bash",
    [Skill.Block]: "Block",
    [Skill.BrassInstruments]: "Brass Instruments",
    [Skill.Channeling]: "Channeling",
    [Skill.Conjuration]: "Conjuration",
    [Skill.Defense]: "Defense",
    [Skill.Disarm]: "Disarm",
    [Skill.DisarmTraps]: "Disarm Traps",
    [Skill.Divination]: "Divination",
    [Skill.Dodge]: "Dodge",
    [Skill.DoubleAttack]: "Double Attack",
    [Skill.DragonPunch]: "Dragon Punch",
    [Skill.DualWield]: "Dual Wield",
    [Skill.EagleStrike]: "Eagle Strike",
    [Skill.Evocation]: "Evocation",
    [Skill.FeignDeath]: "Feign Death",
    [Skill.FlyingKick]: "Flying Kick",
    [Skill.Forage]: "Forage",
    [Skill.HandToHand]: "Hand to Hand",
    [Skill.Hide]: "Hide",
    [Skill.Kick]: "Kick",
    [Skill.Meditate]: "Meditate",
    [Skill.Mend]: "Mend",
    [Skill.Offense]: "Offense",
    [Skill.Parry]: "Parry",
    [Skill.PickLock]: "Pick Lock",
    [Skill.OneHPiercing]: "1H Piercing",
    [Skill.Riposte]: "Riposte",
    [Skill.RoundKick]: "Round Kick",
    [Skill.SafeFall]: "Safe Fall",
    [Skill.SenseHeading]: "Sense Heading",
    [Skill.Singing]: "Singing",
    [Skill.Sneak]: "Sneak",
    [Skill.SpecializeAbjure]: "Specialize Abjure",
    [Skill.SpecializeAlteration]: "Specialize Alteration",
    [Skill.SpecializeConjuration]: "Specialize Conjuration",
    [Skill.SpecializeDivination]: "Specialize Divination",
    [Skill.SpecializeEvocation]: "Specialize Evocation",
    [Skill.PickPockets]: "Pick Pockets",
    [Skill.StringedInstruments]: "Stringed Instruments",
    [Skill.Swimming]: "Swimming",
    [Skill.Throwing]: "Throwing",
    [Skill.TigerClaw]: "Tiger Claw",
    [Skill.Tracking]: "Tracking",
    [Skill.WindInstruments]: "Wind Instruments",
    [Skill.Fishing]: "Fishing",
    [Skill.MakePoison]: "Make Poison",
    [Skill.Tinkering]: "Tinkering",
    [Skill.Research]: "Research",
    [Skill.Alchemy]: "Alchemy",
    [Skill.Baking]: "Baking",
    [Skill.Tailoring]: "Tailoring",
    [Skill.SenseTraps]: "Sense Traps",
    [Skill.Blacksmithing]: "Blacksmithing",
    [Skill.Fletching]: "Fletching",
    [Skill.Brewing]: "Brewing",
    [Skill.AlcoholTolerance]: "Alcohol Tolerance",
    [Skill.Begging]: "Begging",
    [Skill.JewelryMaking]: "Jewelry Making",
    [Skill.Pottery]: "Pottery",
    [Skill.PercussionInstruments]: "Percussion Instruments",
    [Skill.Intimidation]: "Intimidation",
    [Skill.Berserking]: "Berserking",
    [Skill.Taunt]: "Taunt",
    [Skill.Frenzy]: "Frenzy",
    [Skill.RemoveTrap]: "Remove Trap",
    [Skill.TripleAttack]: "Triple Attack",
    [Skill.TwoHPiercing]: "2H Piercing",
  };

  return names[skill] || "Unknown";
}
