export default interface Zone {
  short_name: string;
  id: number;
  file_name: string | null;
  long_name: string;
  map_file_name: string | null;
  safe_x: number;
  safe_y: number;
  safe_z: number;
  safe_heading: number;
  graveyard_id: number;
  min_level: number;
  min_status: number;
  zoneidnumber: number;
  timezone: number;
  maxclients: number;
  ruleset: number;
  note: string | null;
  underworld: number;
  minclip: number;
  maxclip: number;
  fog_minclip: number;
  fog_maxclip: number;
  fog_blue: number;
  fog_red: number;
  fog_green: number;
  sky: number;
  ztype: number;
  zone_exp_multiplier: number;
  gravity: number;
  time_type: number;
  fog_red1: number;
  fog_green1: number;
  fog_blue1: number;
  fog_minclip1: number;
  fog_maxclip1: number;
  fog_density: number;
  flag_needed: string;
  canbind: number;
  cancombat: number;
  canlevitate: number;
  castoutdoor: number;
  hotzone: number;
  peqzone: number;
  expansion: number;
  suspendbuffs: number;
  rain_chance1: number;
  rain_duration1: number;
  snow_chance1: number;
  snow_duration1: number;
  type: number;
  skylock: number;
  skip_los: number;
  music: number;
  random_loc: number;
  never_idle: number;
  castdungeon: number;
  pull_limit: number;
  graveyard_time: number;
  max_z: number;
  min_expansion: number;
  max_expansion: number;
  content_flags: string | null;
  content_flags_disabled: string | null;
}
