// Reusing the same MessageType enum from the client for consistency
export enum MessageType {
  SYSTEM = "SYSTEM",
  COMBAT_OUTGOING = "COMBAT_OUTGOING",
  COMBAT_INCOMING = "COMBAT_INCOMING",
  EMOTE = "EMOTE",
  SPELL_CAST = "SPELL_CAST",
  LOCAL_CHAT = "LOCAL_CHAT",
  SHOUT = "SHOUT",
  OOC = "OOC",
  WHO_LOOKUP = "WHO_LOOKUP",
  PRIVATE_MESSAGE = "PRIVATE_MESSAGE",
  GROUP_CHAT = "GROUP_CHAT",
  EXPERIENCE_GAIN = "EXPERIENCE_GAIN",
  SCREENSHOT = "SCREENSHOT",
  LOOT = "LOOT",
  TRADE = "TRADE",
  AUCTION = "AUCTION",
  GUILD_CHAT = "GUILD_CHAT",
  RAID_CHAT = "RAID_CHAT",
  SKILL_INCREASE = "SKILL_INCREASE",
  QUEST_UPDATE = "QUEST_UPDATE",
  ACHIEVEMENT = "ACHIEVEMENT",
  FACTION_CHANGE = "FACTION_CHANGE",
  ZONE_ANNOUNCEMENT = "ZONE_ANNOUNCEMENT",
  DEATH = "DEATH",
  RESURRECTION = "RESURRECTION",
  PARTY_INVITE = "PARTY_INVITE",
  GUILD_INVITE = "GUILD_INVITE",
  FRIEND_STATUS = "FRIEND_STATUS",
  SYSTEM_ERROR = "SYSTEM_ERROR",
  COMBAT_SPECIAL = "COMBAT_SPECIAL",
}

export interface ChatMessage {
  id: number | string;
  text: string;
  timestamp: number;
  type: MessageType;
}
