// Code generated by 'yaegi extract idlequest/internal/quest/zones/qeynos'. DO NOT EDIT.

package yaegi_wrappers

import (
	"idlequest/internal/quest/zones/qeynos"
	"reflect"
)

func init() {
	Symbols["idlequest/internal/quest/zones/qeynos/qeynos"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"RegisterZone": reflect.ValueOf(qeynos.RegisterZone),
	}
}
