//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type AdventureMembers struct {
	ID     uint32
	Charid uint32 `sql:"primary_key"`
}
