//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type AdventureStats struct {
	PlayerID  uint32 `sql:"primary_key"`
	GukWins   uint32
	MirWins   uint32
	MmcWins   uint32
	RujWins   uint32
	TakWins   uint32
	GukLosses uint32
	MirLosses uint32
	MmcLosses uint32
	RujLosses uint32
	TakLosses uint32
}
