//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type CharacterData struct {
	ID                 uint32 `sql:"primary_key"`
	AccountID          int32
	Name               string
	LastName           string
	Title              string
	Suffix             string
	ZoneID             uint32
	ZoneInstance       uint32
	Y                  float64
	X                  float64
	Z                  float64
	Heading            float64
	Gender             uint8
	Race               uint16
	Class              uint8
	Level              uint32
	Deity              uint32
	Birthday           uint32
	LastLogin          uint32
	TimePlayed         uint32
	Anon               uint8
	Gm                 uint8
	Face               uint32
	AbilityTimeSeconds uint8
	AbilityNumber      uint8
	AbilityTimeMinutes uint8
	AbilityTimeHours   uint8
	Exp                uint32
	ExpEnabled         uint8
	AaPointsSpent      uint32
	AaExp              uint32
	AaPoints           uint32
	Points             uint32
	CurHp              uint32
	Mana               uint32
	Endurance          uint32
	Intoxication       uint32
	Str                uint32
	Sta                uint32
	Cha                uint32
	Dex                uint32
	Int                uint32
	Agi                uint32
	Wis                uint32
	ExtraHaste         int32
	ZoneChangeCount    uint32
	Toxicity           uint32
	HungerLevel        uint32
	ThirstLevel        uint32
	AbilityUp          uint32
	ShowHelm           uint32
	GroupAutoConsent   uint8
	RaidAutoConsent    uint8
	GuildAutoConsent   uint8
	RestTimer          uint32
	AirRemaining       uint32
	AutosplitEnabled   uint32
	Lfp                uint8
	Lfg                uint8
	Mailkey            string
	Xtargets           uint8
	Firstlogon         int8
	EAaEffects         uint32
	EPercentToAa       uint32
	EExpendedAaSpent   uint32
	AaPointsSpentOld   uint32
	AaPointsOld        uint32
	DeletedAt          *time.Time
	IllusionBlock      uint8
	Wind               uint32
	Brass              uint32
	String             uint32
	Percussion         uint32
	Singing            uint32
	Baking             uint32
	Alchemy            uint32
	Tailoring          uint32
	Blacksmithing      uint32
	Fletching          uint32
	Brewing            uint32
	Jewelry            uint32
	Pottery            uint32
	Research           uint32
	Alcohol            uint32
	Fishing            uint32
	Tinkering          uint32
}
