//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type CharacterStatsRecord struct {
	CharacterID            int32 `sql:"primary_key"`
	Name                   *string
	Status                 *int32
	Level                  *int32
	Class                  *int32
	Race                   *int32
	AaPoints               *int32
	Hp                     *int64
	Mana                   *int64
	Endurance              *int64
	Ac                     *int32
	Strength               *int32
	Stamina                *int32
	Dexterity              *int32
	Agility                *int32
	Intelligence           *int32
	Wisdom                 *int32
	Charisma               *int32
	MagicResist            *int32
	FireResist             *int32
	ColdResist             *int32
	PoisonResist           *int32
	DiseaseResist          *int32
	CorruptionResist       *int32
	HeroicStrength         *int32
	HeroicStamina          *int32
	HeroicDexterity        *int32
	HeroicAgility          *int32
	HeroicIntelligence     *int32
	HeroicWisdom           *int32
	HeroicCharisma         *int32
	HeroicMagicResist      *int32
	HeroicFireResist       *int32
	HeroicColdResist       *int32
	HeroicPoisonResist     *int32
	HeroicDiseaseResist    *int32
	HeroicCorruptionResist *int32
	Haste                  *int32
	Accuracy               *int32
	Attack                 *int32
	Avoidance              *int32
	Clairvoyance           *int32
	CombatEffects          *int32
	DamageShieldMitigation *int32
	DamageShield           *int32
	DotShielding           *int32
	HpRegen                *int32
	ManaRegen              *int32
	EnduranceRegen         *int32
	Shielding              *int32
	SpellDamage            *int32
	SpellShielding         *int32
	Strikethrough          *int32
	StunResist             *int32
	Backstab               *int32
	Wind                   *int32
	Brass                  *int32
	String                 *int32
	Percussion             *int32
	Singing                *int32
	Baking                 *int32
	Alchemy                *int32
	Tailoring              *int32
	Blacksmithing          *int32
	Fletching              *int32
	Brewing                *int32
	Jewelry                *int32
	Pottery                *int32
	Research               *int32
	Alcohol                *int32
	Fishing                *int32
	Tinkering              *int32
	CreatedAt              *time.Time
	UpdatedAt              *time.Time
}
