//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type CharacterCurrency struct {
	ID                    uint32 `sql:"primary_key"`
	Platinum              uint32
	Gold                  uint32
	Silver                uint32
	Copper                uint32
	PlatinumBank          uint32
	GoldBank              uint32
	SilverBank            uint32
	CopperBank            uint32
	PlatinumCursor        uint32
	GoldCursor            uint32
	SilverCursor          uint32
	CopperCursor          uint32
	RadiantCrystals       uint32
	CareerRadiantCrystals uint32
	EbonCrystals          uint32
	CareerEbonCrystals    uint32
}
