//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type CharacterTaskTimers struct {
	ID          uint32 `sql:"primary_key"`
	CharacterID uint32
	TaskID      uint32
	TimerType   int32
	TimerGroup  int32
	ExpireTime  time.Time
}
