//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

// CharCreateData represents a row in the char_create_data table
type CharCreateData struct {
	ID           int32   `sql:"primary_key" json:"id"`
	Category     string  `json:"category"`
	Name         string  `json:"name"`
	AltName      *string `json:"alt_name"`
	Description  *string `json:"description"`
	EqstrIDStart *int32  `json:"eqstr_id_start"`
	EqstrIDEnd   *int32  `json:"eqstr_id_end"`
	GameID       *int32  `json:"game_id"`
}
