//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type CombinationDescriptions struct {
	ID          int32 `sql:"primary_key"`
	ClassID     int32
	RaceID      int32
	DeityID     int32
	Description *string
}
