//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type GridEntries struct {
	Gridid      int32 `sql:"primary_key"`
	Zoneid      int32 `sql:"primary_key"`
	Number      int32 `sql:"primary_key"`
	X           float64
	Y           float64
	Z           float64
	Heading     float64
	Pause       int32
	Centerpoint int8
}
