//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Guilds struct {
	ID         int32 `sql:"primary_key"`
	Name       string
	Leader     int32
	Minstatus  int16
	Motd       string
	Tribute    uint32
	MotdSetter string
	Channel    string
	URL        string
	Favor      uint32
}
