//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type LoottableEntries struct {
	LoottableID uint32 `sql:"primary_key"`
	LootdropID  uint32 `sql:"primary_key"`
	Multiplier  uint8
	Droplimit   uint8
	Mindrop     uint8
	Probability float64
}
