//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Merchantlist struct {
	Merchantid           int32  `sql:"primary_key"`
	Slot                 uint32 `sql:"primary_key"`
	Item                 int32
	CustomData           *string
	FactionRequired      int16
	LevelRequired        uint8
	MinStatus            uint8
	MaxStatus            uint8
	AltCurrencyCost      uint16
	ClassesRequired      int32
	Probability          int32
	BucketName           string
	BucketValue          string
	BucketComparison     *uint8
	MinExpansion         int8
	MaxExpansion         int8
	ContentFlags         *string
	ContentFlagsDisabled *string
}
