//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type NpcScaleGlobalBase struct {
	Type                int32  `sql:"primary_key"`
	Level               int32  `sql:"primary_key"`
	ZoneIDList          string `sql:"primary_key"`
	InstanceVersionList string `sql:"primary_key"`
	Ac                  int32
	Hp                  int64
	Accuracy            int32
	SlowMitigation      int32
	Attack              int32
	Strength            int32
	Stamina             int32
	Dexterity           int32
	Agility             int32
	Intelligence        int32
	Wisdom              int32
	Charisma            int32
	MagicResist         int32
	ColdResist          int32
	FireResist          int32
	PoisonResist        int32
	DiseaseResist       int32
	CorruptionResist    int32
	PhysicalResist      int32
	MinDmg              int32
	MaxDmg              int32
	HpRegenRate         int64
	HpRegenPerSecond    int64
	AttackDelay         int32
	SpellScale          int32
	HealScale           int32
	Avoidance           uint32
	HeroicStrikethrough int32
	SpecialAbilities    string
}
