//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type NpcSpells struct {
	ID                   uint32 `sql:"primary_key"`
	Name                 *string
	ParentList           uint32
	AttackProc           int16
	ProcChance           int8
	RangeProc            int16
	RprocChance          int16
	DefensiveProc        int16
	DprocChance          int16
	FailRecast           uint32
	EngagedNoSpRecastMin uint32
	EngagedNoSpRecastMax uint32
	EngagedBSelfChance   uint8
	EngagedBOtherChance  uint8
	EngagedDChance       uint8
	PursueNoSpRecastMin  uint32
	PursueNoSpRecastMax  uint32
	PursueDChance        uint8
	IdleNoSpRecastMin    uint32
	IdleNoSpRecastMax    uint32
	IdleBChance          uint8
}
