//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type NpcTypesTint struct {
	ID          uint32 `sql:"primary_key"`
	TintSetName string
	Red1h       uint8
	Grn1h       uint8
	Blu1h       uint8
	Red2c       uint8
	Grn2c       uint8
	Blu2c       uint8
	Red3a       uint8
	Grn3a       uint8
	Blu3a       uint8
	Red4b       uint8
	Grn4b       uint8
	Blu4b       uint8
	Red5g       uint8
	Grn5g       uint8
	Blu5g       uint8
	Red6l       uint8
	Grn6l       uint8
	Blu6l       uint8
	Red7f       uint8
	Grn7f       uint8
	Blu7f       uint8
	Red8x       uint8
	Grn8x       uint8
	Blu8x       uint8
	Red9x       uint8
	Grn9x       uint8
	Blu9x       uint8
}
