//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type PlayerEventTrade struct {
	ID            uint32 `sql:"primary_key"`
	Char1ID       *uint32
	Char2ID       *uint32
	Char1Copper   *uint64
	Char1Silver   *uint64
	Char1Gold     *uint64
	Char1Platinum *uint64
	Char2Copper   *uint64
	Char2Silver   *uint64
	Char2Gold     *uint64
	Char2Platinum *uint64
	CreatedAt     *time.Time
}
