//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type QsPlayerMoveRecord struct {
	MoveID     int32 `sql:"primary_key"`
	Time       *time.Time
	CharID     *int32
	FromSlot   *int32
	ToSlot     *int32
	StackSize  *int32
	CharItems  *int32
	Postaction *bool
}
