//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type RaidLeaders struct {
	Gid           uint32
	Rid           uint32
	Marknpc       string
	Maintank      string
	Assist        string
	Puller        string
	Leadershipaa  []byte
	Mentoree      string
	MentorPercent int32
}
