//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type SharedTaskMembers struct {
	SharedTaskID int64 `sql:"primary_key"`
	CharacterID  int64 `sql:"primary_key"`
	IsLeader     *int8
}
