//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Spawnentry struct {
	SpawngroupID         int32 `sql:"primary_key"`
	NpcID                int32 `sql:"primary_key"`
	Chance               int16
	ConditionValueFilter int32
	MinTime              int16
	MaxTime              int16
	MinExpansion         int8
	MaxExpansion         int8
	ContentFlags         *string
	ContentFlagsDisabled *string
}
