//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SpireUserServerDatabaseConnections struct {
	ID                         uint64 `sql:"primary_key"`
	UserID                     *uint64
	ServerDatabaseConnectionID *uint64
	Active                     *uint64
	CreatedBy                  *uint64
	CreatedAt                  *time.Time
	UpdatedAt                  *time.Time
	DeletedAt                  *time.Time
}
