//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Tributes struct {
	ID      uint32 `sql:"primary_key"`
	Unknown uint32
	Name    string
	Descr   string
	Isguild int8 `sql:"primary_key"`
}
