//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Eqtime = newEqtimeTable("eqgo", "eqtime", "")

type eqtimeTable struct {
	mysql.Table

	// Columns
	Minute   mysql.ColumnInteger
	Hour     mysql.ColumnInteger
	Day      mysql.ColumnInteger
	Month    mysql.ColumnInteger
	Year     mysql.ColumnInteger
	Realtime mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type EqtimeTable struct {
	eqtimeTable

	NEW eqtimeTable
}

// AS creates new EqtimeTable with assigned alias
func (a EqtimeTable) AS(alias string) *EqtimeTable {
	return newEqtimeTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EqtimeTable with assigned schema name
func (a EqtimeTable) FromSchema(schemaName string) *EqtimeTable {
	return newEqtimeTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EqtimeTable with assigned table prefix
func (a EqtimeTable) WithPrefix(prefix string) *EqtimeTable {
	return newEqtimeTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EqtimeTable with assigned table suffix
func (a EqtimeTable) WithSuffix(suffix string) *EqtimeTable {
	return newEqtimeTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEqtimeTable(schemaName, tableName, alias string) *EqtimeTable {
	return &EqtimeTable{
		eqtimeTable: newEqtimeTableImpl(schemaName, tableName, alias),
		NEW:         newEqtimeTableImpl("", "new", ""),
	}
}

func newEqtimeTableImpl(schemaName, tableName, alias string) eqtimeTable {
	var (
		MinuteColumn   = mysql.IntegerColumn("minute")
		HourColumn     = mysql.IntegerColumn("hour")
		DayColumn      = mysql.IntegerColumn("day")
		MonthColumn    = mysql.IntegerColumn("month")
		YearColumn     = mysql.IntegerColumn("year")
		RealtimeColumn = mysql.IntegerColumn("realtime")
		allColumns     = mysql.ColumnList{MinuteColumn, HourColumn, DayColumn, MonthColumn, YearColumn, RealtimeColumn}
		mutableColumns = mysql.ColumnList{MinuteColumn, HourColumn, DayColumn, MonthColumn, YearColumn, RealtimeColumn}
		defaultColumns = mysql.ColumnList{MinuteColumn, HourColumn, DayColumn, MonthColumn, YearColumn, RealtimeColumn}
	)

	return eqtimeTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Minute:   MinuteColumn,
		Hour:     HourColumn,
		Day:      DayColumn,
		Month:    MonthColumn,
		Year:     YearColumn,
		Realtime: RealtimeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
