//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Guilds = newGuildsTable("eqgo", "guilds", "")

type guildsTable struct {
	mysql.Table

	// Columns
	ID         mysql.ColumnInteger
	Name       mysql.ColumnString
	Leader     mysql.ColumnInteger
	Minstatus  mysql.ColumnInteger
	Motd       mysql.ColumnString
	Tribute    mysql.ColumnInteger
	MotdSetter mysql.ColumnString
	Channel    mysql.ColumnString
	URL        mysql.ColumnString
	Favor      mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type GuildsTable struct {
	guildsTable

	NEW guildsTable
}

// AS creates new GuildsTable with assigned alias
func (a GuildsTable) AS(alias string) *GuildsTable {
	return newGuildsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new GuildsTable with assigned schema name
func (a GuildsTable) FromSchema(schemaName string) *GuildsTable {
	return newGuildsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new GuildsTable with assigned table prefix
func (a GuildsTable) WithPrefix(prefix string) *GuildsTable {
	return newGuildsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new GuildsTable with assigned table suffix
func (a GuildsTable) WithSuffix(suffix string) *GuildsTable {
	return newGuildsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newGuildsTable(schemaName, tableName, alias string) *GuildsTable {
	return &GuildsTable{
		guildsTable: newGuildsTableImpl(schemaName, tableName, alias),
		NEW:         newGuildsTableImpl("", "new", ""),
	}
}

func newGuildsTableImpl(schemaName, tableName, alias string) guildsTable {
	var (
		IDColumn         = mysql.IntegerColumn("id")
		NameColumn       = mysql.StringColumn("name")
		LeaderColumn     = mysql.IntegerColumn("leader")
		MinstatusColumn  = mysql.IntegerColumn("minstatus")
		MotdColumn       = mysql.StringColumn("motd")
		TributeColumn    = mysql.IntegerColumn("tribute")
		MotdSetterColumn = mysql.StringColumn("motd_setter")
		ChannelColumn    = mysql.StringColumn("channel")
		URLColumn        = mysql.StringColumn("url")
		FavorColumn      = mysql.IntegerColumn("favor")
		allColumns       = mysql.ColumnList{IDColumn, NameColumn, LeaderColumn, MinstatusColumn, MotdColumn, TributeColumn, MotdSetterColumn, ChannelColumn, URLColumn, FavorColumn}
		mutableColumns   = mysql.ColumnList{NameColumn, LeaderColumn, MinstatusColumn, MotdColumn, TributeColumn, MotdSetterColumn, ChannelColumn, URLColumn, FavorColumn}
		defaultColumns   = mysql.ColumnList{NameColumn, LeaderColumn, MinstatusColumn, TributeColumn, MotdSetterColumn, ChannelColumn, URLColumn, FavorColumn}
	)

	return guildsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		Name:       NameColumn,
		Leader:     LeaderColumn,
		Minstatus:  MinstatusColumn,
		Motd:       MotdColumn,
		Tribute:    TributeColumn,
		MotdSetter: MotdSetterColumn,
		Channel:    ChannelColumn,
		URL:        URLColumn,
		Favor:      FavorColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
