//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Lfguild = newLfguildTable("eqgo", "lfguild", "")

type lfguildTable struct {
	mysql.Table

	// Columns
	Type       mysql.ColumnInteger
	Name       mysql.ColumnString
	Comment    mysql.ColumnString
	Fromlevel  mysql.ColumnInteger
	Tolevel    mysql.ColumnInteger
	Classes    mysql.ColumnInteger
	Aacount    mysql.ColumnInteger
	Timezone   mysql.ColumnInteger
	Timeposted mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type LfguildTable struct {
	lfguildTable

	NEW lfguildTable
}

// AS creates new LfguildTable with assigned alias
func (a LfguildTable) AS(alias string) *LfguildTable {
	return newLfguildTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LfguildTable with assigned schema name
func (a LfguildTable) FromSchema(schemaName string) *LfguildTable {
	return newLfguildTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LfguildTable with assigned table prefix
func (a LfguildTable) WithPrefix(prefix string) *LfguildTable {
	return newLfguildTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LfguildTable with assigned table suffix
func (a LfguildTable) WithSuffix(suffix string) *LfguildTable {
	return newLfguildTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLfguildTable(schemaName, tableName, alias string) *LfguildTable {
	return &LfguildTable{
		lfguildTable: newLfguildTableImpl(schemaName, tableName, alias),
		NEW:          newLfguildTableImpl("", "new", ""),
	}
}

func newLfguildTableImpl(schemaName, tableName, alias string) lfguildTable {
	var (
		TypeColumn       = mysql.IntegerColumn("type")
		NameColumn       = mysql.StringColumn("name")
		CommentColumn    = mysql.StringColumn("comment")
		FromlevelColumn  = mysql.IntegerColumn("fromlevel")
		TolevelColumn    = mysql.IntegerColumn("tolevel")
		ClassesColumn    = mysql.IntegerColumn("classes")
		AacountColumn    = mysql.IntegerColumn("aacount")
		TimezoneColumn   = mysql.IntegerColumn("timezone")
		TimepostedColumn = mysql.IntegerColumn("timeposted")
		allColumns       = mysql.ColumnList{TypeColumn, NameColumn, CommentColumn, FromlevelColumn, TolevelColumn, ClassesColumn, AacountColumn, TimezoneColumn, TimepostedColumn}
		mutableColumns   = mysql.ColumnList{CommentColumn, FromlevelColumn, TolevelColumn, ClassesColumn, AacountColumn, TimezoneColumn, TimepostedColumn}
		defaultColumns   = mysql.ColumnList{TypeColumn, FromlevelColumn, TolevelColumn, ClassesColumn, AacountColumn, TimezoneColumn, TimepostedColumn}
	)

	return lfguildTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Type:       TypeColumn,
		Name:       NameColumn,
		Comment:    CommentColumn,
		Fromlevel:  FromlevelColumn,
		Tolevel:    TolevelColumn,
		Classes:    ClassesColumn,
		Aacount:    AacountColumn,
		Timezone:   TimezoneColumn,
		Timeposted: TimepostedColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
