//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Object = newObjectTable("eqgo", "object", "")

type objectTable struct {
	mysql.Table

	// Columns
	ID                   mysql.ColumnInteger
	Zoneid               mysql.ColumnInteger
	Version              mysql.ColumnInteger
	Xpos                 mysql.ColumnFloat
	Ypos                 mysql.ColumnFloat
	Zpos                 mysql.ColumnFloat
	Heading              mysql.ColumnFloat
	Itemid               mysql.ColumnInteger
	Charges              mysql.ColumnInteger
	Objectname           mysql.ColumnString
	Type                 mysql.ColumnInteger
	Icon                 mysql.ColumnInteger
	SizePercentage       mysql.ColumnFloat
	Unknown24            mysql.ColumnInteger
	Unknown60            mysql.ColumnInteger
	Unknown64            mysql.ColumnInteger
	Unknown68            mysql.ColumnInteger
	Unknown72            mysql.ColumnInteger
	Unknown76            mysql.ColumnInteger
	Unknown84            mysql.ColumnInteger
	Size                 mysql.ColumnFloat
	SolidType            mysql.ColumnInteger
	Incline              mysql.ColumnInteger
	TiltX                mysql.ColumnFloat
	TiltY                mysql.ColumnFloat
	DisplayName          mysql.ColumnString
	MinExpansion         mysql.ColumnInteger
	MaxExpansion         mysql.ColumnInteger
	ContentFlags         mysql.ColumnString
	ContentFlagsDisabled mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type ObjectTable struct {
	objectTable

	NEW objectTable
}

// AS creates new ObjectTable with assigned alias
func (a ObjectTable) AS(alias string) *ObjectTable {
	return newObjectTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ObjectTable with assigned schema name
func (a ObjectTable) FromSchema(schemaName string) *ObjectTable {
	return newObjectTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ObjectTable with assigned table prefix
func (a ObjectTable) WithPrefix(prefix string) *ObjectTable {
	return newObjectTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ObjectTable with assigned table suffix
func (a ObjectTable) WithSuffix(suffix string) *ObjectTable {
	return newObjectTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newObjectTable(schemaName, tableName, alias string) *ObjectTable {
	return &ObjectTable{
		objectTable: newObjectTableImpl(schemaName, tableName, alias),
		NEW:         newObjectTableImpl("", "new", ""),
	}
}

func newObjectTableImpl(schemaName, tableName, alias string) objectTable {
	var (
		IDColumn                   = mysql.IntegerColumn("id")
		ZoneidColumn               = mysql.IntegerColumn("zoneid")
		VersionColumn              = mysql.IntegerColumn("version")
		XposColumn                 = mysql.FloatColumn("xpos")
		YposColumn                 = mysql.FloatColumn("ypos")
		ZposColumn                 = mysql.FloatColumn("zpos")
		HeadingColumn              = mysql.FloatColumn("heading")
		ItemidColumn               = mysql.IntegerColumn("itemid")
		ChargesColumn              = mysql.IntegerColumn("charges")
		ObjectnameColumn           = mysql.StringColumn("objectname")
		TypeColumn                 = mysql.IntegerColumn("type")
		IconColumn                 = mysql.IntegerColumn("icon")
		SizePercentageColumn       = mysql.FloatColumn("size_percentage")
		Unknown24Column            = mysql.IntegerColumn("unknown24")
		Unknown60Column            = mysql.IntegerColumn("unknown60")
		Unknown64Column            = mysql.IntegerColumn("unknown64")
		Unknown68Column            = mysql.IntegerColumn("unknown68")
		Unknown72Column            = mysql.IntegerColumn("unknown72")
		Unknown76Column            = mysql.IntegerColumn("unknown76")
		Unknown84Column            = mysql.IntegerColumn("unknown84")
		SizeColumn                 = mysql.FloatColumn("size")
		SolidTypeColumn            = mysql.IntegerColumn("solid_type")
		InclineColumn              = mysql.IntegerColumn("incline")
		TiltXColumn                = mysql.FloatColumn("tilt_x")
		TiltYColumn                = mysql.FloatColumn("tilt_y")
		DisplayNameColumn          = mysql.StringColumn("display_name")
		MinExpansionColumn         = mysql.IntegerColumn("min_expansion")
		MaxExpansionColumn         = mysql.IntegerColumn("max_expansion")
		ContentFlagsColumn         = mysql.StringColumn("content_flags")
		ContentFlagsDisabledColumn = mysql.StringColumn("content_flags_disabled")
		allColumns                 = mysql.ColumnList{IDColumn, ZoneidColumn, VersionColumn, XposColumn, YposColumn, ZposColumn, HeadingColumn, ItemidColumn, ChargesColumn, ObjectnameColumn, TypeColumn, IconColumn, SizePercentageColumn, Unknown24Column, Unknown60Column, Unknown64Column, Unknown68Column, Unknown72Column, Unknown76Column, Unknown84Column, SizeColumn, SolidTypeColumn, InclineColumn, TiltXColumn, TiltYColumn, DisplayNameColumn, MinExpansionColumn, MaxExpansionColumn, ContentFlagsColumn, ContentFlagsDisabledColumn}
		mutableColumns             = mysql.ColumnList{ZoneidColumn, VersionColumn, XposColumn, YposColumn, ZposColumn, HeadingColumn, ItemidColumn, ChargesColumn, ObjectnameColumn, TypeColumn, IconColumn, SizePercentageColumn, Unknown24Column, Unknown60Column, Unknown64Column, Unknown68Column, Unknown72Column, Unknown76Column, Unknown84Column, SizeColumn, SolidTypeColumn, InclineColumn, TiltXColumn, TiltYColumn, DisplayNameColumn, MinExpansionColumn, MaxExpansionColumn, ContentFlagsColumn, ContentFlagsDisabledColumn}
		defaultColumns             = mysql.ColumnList{ZoneidColumn, VersionColumn, XposColumn, YposColumn, ZposColumn, HeadingColumn, ItemidColumn, ChargesColumn, TypeColumn, IconColumn, SizePercentageColumn, Unknown24Column, Unknown60Column, Unknown64Column, Unknown68Column, Unknown72Column, Unknown76Column, Unknown84Column, SizeColumn, SolidTypeColumn, InclineColumn, TiltXColumn, TiltYColumn, MinExpansionColumn, MaxExpansionColumn}
	)

	return objectTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                   IDColumn,
		Zoneid:               ZoneidColumn,
		Version:              VersionColumn,
		Xpos:                 XposColumn,
		Ypos:                 YposColumn,
		Zpos:                 ZposColumn,
		Heading:              HeadingColumn,
		Itemid:               ItemidColumn,
		Charges:              ChargesColumn,
		Objectname:           ObjectnameColumn,
		Type:                 TypeColumn,
		Icon:                 IconColumn,
		SizePercentage:       SizePercentageColumn,
		Unknown24:            Unknown24Column,
		Unknown60:            Unknown60Column,
		Unknown64:            Unknown64Column,
		Unknown68:            Unknown68Column,
		Unknown72:            Unknown72Column,
		Unknown76:            Unknown76Column,
		Unknown84:            Unknown84Column,
		Size:                 SizeColumn,
		SolidType:            SolidTypeColumn,
		Incline:              InclineColumn,
		TiltX:                TiltXColumn,
		TiltY:                TiltYColumn,
		DisplayName:          DisplayNameColumn,
		MinExpansion:         MinExpansionColumn,
		MaxExpansion:         MaxExpansionColumn,
		ContentFlags:         ContentFlagsColumn,
		ContentFlagsDisabled: ContentFlagsDisabledColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
