//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var RespawnTimes = newRespawnTimesTable("peq", "respawn_times", "")

type respawnTimesTable struct {
	mysql.Table

	// Columns
	ID         mysql.ColumnInteger
	Start      mysql.ColumnInteger
	Duration   mysql.ColumnInteger
	InstanceID mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type RespawnTimesTable struct {
	respawnTimesTable

	NEW respawnTimesTable
}

// AS creates new RespawnTimesTable with assigned alias
func (a RespawnTimesTable) AS(alias string) *RespawnTimesTable {
	return newRespawnTimesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RespawnTimesTable with assigned schema name
func (a RespawnTimesTable) FromSchema(schemaName string) *RespawnTimesTable {
	return newRespawnTimesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RespawnTimesTable with assigned table prefix
func (a RespawnTimesTable) WithPrefix(prefix string) *RespawnTimesTable {
	return newRespawnTimesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RespawnTimesTable with assigned table suffix
func (a RespawnTimesTable) WithSuffix(suffix string) *RespawnTimesTable {
	return newRespawnTimesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRespawnTimesTable(schemaName, tableName, alias string) *RespawnTimesTable {
	return &RespawnTimesTable{
		respawnTimesTable: newRespawnTimesTableImpl(schemaName, tableName, alias),
		NEW:               newRespawnTimesTableImpl("", "new", ""),
	}
}

func newRespawnTimesTableImpl(schemaName, tableName, alias string) respawnTimesTable {
	var (
		IDColumn         = mysql.IntegerColumn("id")
		StartColumn      = mysql.IntegerColumn("start")
		DurationColumn   = mysql.IntegerColumn("duration")
		InstanceIDColumn = mysql.IntegerColumn("instance_id")
		allColumns       = mysql.ColumnList{IDColumn, StartColumn, DurationColumn, InstanceIDColumn}
		mutableColumns   = mysql.ColumnList{StartColumn, DurationColumn}
		defaultColumns   = mysql.ColumnList{IDColumn, StartColumn, DurationColumn, InstanceIDColumn}
	)

	return respawnTimesTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		Start:      StartColumn,
		Duration:   DurationColumn,
		InstanceID: InstanceIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
