//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Sharedbank = newSharedbankTable("peq", "sharedbank", "")

type sharedbankTable struct {
	mysql.Table

	// Columns
	AccountID         mysql.ColumnInteger
	SlotID            mysql.ColumnInteger
	ItemID            mysql.ColumnInteger
	Charges           mysql.ColumnInteger
	Color             mysql.ColumnInteger
	AugmentOne        mysql.ColumnInteger
	AugmentTwo        mysql.ColumnInteger
	AugmentThree      mysql.ColumnInteger
	AugmentFour       mysql.ColumnInteger
	AugmentFive       mysql.ColumnInteger
	AugmentSix        mysql.ColumnInteger
	CustomData        mysql.ColumnString
	OrnamentIcon      mysql.ColumnInteger
	OrnamentIdfile    mysql.ColumnInteger
	OrnamentHeroModel mysql.ColumnInteger
	GUID              mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type SharedbankTable struct {
	sharedbankTable

	NEW sharedbankTable
}

// AS creates new SharedbankTable with assigned alias
func (a SharedbankTable) AS(alias string) *SharedbankTable {
	return newSharedbankTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SharedbankTable with assigned schema name
func (a SharedbankTable) FromSchema(schemaName string) *SharedbankTable {
	return newSharedbankTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SharedbankTable with assigned table prefix
func (a SharedbankTable) WithPrefix(prefix string) *SharedbankTable {
	return newSharedbankTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SharedbankTable with assigned table suffix
func (a SharedbankTable) WithSuffix(suffix string) *SharedbankTable {
	return newSharedbankTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSharedbankTable(schemaName, tableName, alias string) *SharedbankTable {
	return &SharedbankTable{
		sharedbankTable: newSharedbankTableImpl(schemaName, tableName, alias),
		NEW:             newSharedbankTableImpl("", "new", ""),
	}
}

func newSharedbankTableImpl(schemaName, tableName, alias string) sharedbankTable {
	var (
		AccountIDColumn         = mysql.IntegerColumn("account_id")
		SlotIDColumn            = mysql.IntegerColumn("slot_id")
		ItemIDColumn            = mysql.IntegerColumn("item_id")
		ChargesColumn           = mysql.IntegerColumn("charges")
		ColorColumn             = mysql.IntegerColumn("color")
		AugmentOneColumn        = mysql.IntegerColumn("augment_one")
		AugmentTwoColumn        = mysql.IntegerColumn("augment_two")
		AugmentThreeColumn      = mysql.IntegerColumn("augment_three")
		AugmentFourColumn       = mysql.IntegerColumn("augment_four")
		AugmentFiveColumn       = mysql.IntegerColumn("augment_five")
		AugmentSixColumn        = mysql.IntegerColumn("augment_six")
		CustomDataColumn        = mysql.StringColumn("custom_data")
		OrnamentIconColumn      = mysql.IntegerColumn("ornament_icon")
		OrnamentIdfileColumn    = mysql.IntegerColumn("ornament_idfile")
		OrnamentHeroModelColumn = mysql.IntegerColumn("ornament_hero_model")
		GUIDColumn              = mysql.IntegerColumn("guid")
		allColumns              = mysql.ColumnList{AccountIDColumn, SlotIDColumn, ItemIDColumn, ChargesColumn, ColorColumn, AugmentOneColumn, AugmentTwoColumn, AugmentThreeColumn, AugmentFourColumn, AugmentFiveColumn, AugmentSixColumn, CustomDataColumn, OrnamentIconColumn, OrnamentIdfileColumn, OrnamentHeroModelColumn, GUIDColumn}
		mutableColumns          = mysql.ColumnList{ItemIDColumn, ChargesColumn, ColorColumn, AugmentOneColumn, AugmentTwoColumn, AugmentThreeColumn, AugmentFourColumn, AugmentFiveColumn, AugmentSixColumn, CustomDataColumn, OrnamentIconColumn, OrnamentIdfileColumn, OrnamentHeroModelColumn, GUIDColumn}
		defaultColumns          = mysql.ColumnList{AccountIDColumn, SlotIDColumn, ItemIDColumn, ChargesColumn, ColorColumn, AugmentOneColumn, AugmentTwoColumn, AugmentThreeColumn, AugmentFourColumn, AugmentFiveColumn, AugmentSixColumn, GUIDColumn}
	)

	return sharedbankTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		AccountID:         AccountIDColumn,
		SlotID:            SlotIDColumn,
		ItemID:            ItemIDColumn,
		Charges:           ChargesColumn,
		Color:             ColorColumn,
		AugmentOne:        AugmentOneColumn,
		AugmentTwo:        AugmentTwoColumn,
		AugmentThree:      AugmentThreeColumn,
		AugmentFour:       AugmentFourColumn,
		AugmentFive:       AugmentFiveColumn,
		AugmentSix:        AugmentSixColumn,
		CustomData:        CustomDataColumn,
		OrnamentIcon:      OrnamentIconColumn,
		OrnamentIdfile:    OrnamentIdfileColumn,
		OrnamentHeroModel: OrnamentHeroModelColumn,
		GUID:              GUIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
