//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var SkillCaps = newSkillCapsTable("peq", "skill_caps", "")

type skillCapsTable struct {
	mysql.Table

	// Columns
	ID      mysql.ColumnInteger
	SkillID mysql.ColumnInteger
	ClassID mysql.ColumnInteger
	Level   mysql.ColumnInteger
	Cap     mysql.ColumnInteger
	Class   mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type SkillCapsTable struct {
	skillCapsTable

	NEW skillCapsTable
}

// AS creates new SkillCapsTable with assigned alias
func (a SkillCapsTable) AS(alias string) *SkillCapsTable {
	return newSkillCapsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SkillCapsTable with assigned schema name
func (a SkillCapsTable) FromSchema(schemaName string) *SkillCapsTable {
	return newSkillCapsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SkillCapsTable with assigned table prefix
func (a SkillCapsTable) WithPrefix(prefix string) *SkillCapsTable {
	return newSkillCapsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SkillCapsTable with assigned table suffix
func (a SkillCapsTable) WithSuffix(suffix string) *SkillCapsTable {
	return newSkillCapsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSkillCapsTable(schemaName, tableName, alias string) *SkillCapsTable {
	return &SkillCapsTable{
		skillCapsTable: newSkillCapsTableImpl(schemaName, tableName, alias),
		NEW:            newSkillCapsTableImpl("", "new", ""),
	}
}

func newSkillCapsTableImpl(schemaName, tableName, alias string) skillCapsTable {
	var (
		IDColumn       = mysql.IntegerColumn("id")
		SkillIDColumn  = mysql.IntegerColumn("skill_id")
		ClassIDColumn  = mysql.IntegerColumn("class_id")
		LevelColumn    = mysql.IntegerColumn("level")
		CapColumn      = mysql.IntegerColumn("cap")
		ClassColumn    = mysql.IntegerColumn("class_")
		allColumns     = mysql.ColumnList{IDColumn, SkillIDColumn, ClassIDColumn, LevelColumn, CapColumn, ClassColumn}
		mutableColumns = mysql.ColumnList{SkillIDColumn, ClassIDColumn, LevelColumn, CapColumn, ClassColumn}
		defaultColumns = mysql.ColumnList{SkillIDColumn, ClassIDColumn, LevelColumn, CapColumn, ClassColumn}
	)

	return skillCapsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:      IDColumn,
		SkillID: SkillIDColumn,
		ClassID: ClassIDColumn,
		Level:   LevelColumn,
		Cap:     CapColumn,
		Class:   ClassColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
