//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Zone = newZoneTable("peq", "zone", "")

type zoneTable struct {
	mysql.Table

	// Columns
	ID                      mysql.ColumnInteger
	Zoneidnumber            mysql.ColumnInteger
	Version                 mysql.ColumnInteger
	ShortName               mysql.ColumnString
	LongName                mysql.ColumnString
	MinStatus               mysql.ColumnInteger
	MapFileName             mysql.ColumnString
	Note                    mysql.ColumnString
	MinExpansion            mysql.ColumnInteger
	MaxExpansion            mysql.ColumnInteger
	ContentFlags            mysql.ColumnString
	ContentFlagsDisabled    mysql.ColumnString
	Expansion               mysql.ColumnInteger
	FileName                mysql.ColumnString
	SafeX                   mysql.ColumnFloat
	SafeY                   mysql.ColumnFloat
	SafeZ                   mysql.ColumnFloat
	SafeHeading             mysql.ColumnFloat
	GraveyardID             mysql.ColumnFloat
	MinLevel                mysql.ColumnInteger
	MaxLevel                mysql.ColumnInteger
	Timezone                mysql.ColumnInteger
	Maxclients              mysql.ColumnInteger
	Ruleset                 mysql.ColumnInteger
	Underworld              mysql.ColumnFloat
	Minclip                 mysql.ColumnFloat
	Maxclip                 mysql.ColumnFloat
	FogMinclip              mysql.ColumnFloat
	FogMaxclip              mysql.ColumnFloat
	FogBlue                 mysql.ColumnInteger
	FogRed                  mysql.ColumnInteger
	FogGreen                mysql.ColumnInteger
	Sky                     mysql.ColumnInteger
	Ztype                   mysql.ColumnInteger
	ZoneExpMultiplier       mysql.ColumnFloat
	Walkspeed               mysql.ColumnFloat
	TimeType                mysql.ColumnInteger
	FogRed1                 mysql.ColumnInteger
	FogGreen1               mysql.ColumnInteger
	FogBlue1                mysql.ColumnInteger
	FogMinclip1             mysql.ColumnFloat
	FogMaxclip1             mysql.ColumnFloat
	FogRed2                 mysql.ColumnInteger
	FogGreen2               mysql.ColumnInteger
	FogBlue2                mysql.ColumnInteger
	FogMinclip2             mysql.ColumnFloat
	FogMaxclip2             mysql.ColumnFloat
	FogRed3                 mysql.ColumnInteger
	FogGreen3               mysql.ColumnInteger
	FogBlue3                mysql.ColumnInteger
	FogMinclip3             mysql.ColumnFloat
	FogMaxclip3             mysql.ColumnFloat
	FogRed4                 mysql.ColumnInteger
	FogGreen4               mysql.ColumnInteger
	FogBlue4                mysql.ColumnInteger
	FogMinclip4             mysql.ColumnFloat
	FogMaxclip4             mysql.ColumnFloat
	FogDensity              mysql.ColumnFloat
	FlagNeeded              mysql.ColumnString
	Canbind                 mysql.ColumnInteger
	Cancombat               mysql.ColumnInteger
	Canlevitate             mysql.ColumnInteger
	Castoutdoor             mysql.ColumnInteger
	Hotzone                 mysql.ColumnInteger
	Insttype                mysql.ColumnInteger
	Shutdowndelay           mysql.ColumnInteger
	Peqzone                 mysql.ColumnInteger
	BypassExpansionCheck    mysql.ColumnInteger
	Suspendbuffs            mysql.ColumnInteger
	RainChance1             mysql.ColumnInteger
	RainChance2             mysql.ColumnInteger
	RainChance3             mysql.ColumnInteger
	RainChance4             mysql.ColumnInteger
	RainDuration1           mysql.ColumnInteger
	RainDuration2           mysql.ColumnInteger
	RainDuration3           mysql.ColumnInteger
	RainDuration4           mysql.ColumnInteger
	SnowChance1             mysql.ColumnInteger
	SnowChance2             mysql.ColumnInteger
	SnowChance3             mysql.ColumnInteger
	SnowChance4             mysql.ColumnInteger
	SnowDuration1           mysql.ColumnInteger
	SnowDuration2           mysql.ColumnInteger
	SnowDuration3           mysql.ColumnInteger
	SnowDuration4           mysql.ColumnInteger
	Gravity                 mysql.ColumnFloat
	Type                    mysql.ColumnInteger
	Skylock                 mysql.ColumnInteger
	FastRegenHp             mysql.ColumnInteger
	FastRegenMana           mysql.ColumnInteger
	FastRegenEndurance      mysql.ColumnInteger
	NpcMaxAggroDist         mysql.ColumnInteger
	ClientUpdateRange       mysql.ColumnInteger
	UnderworldTeleportIndex mysql.ColumnInteger
	LavaDamage              mysql.ColumnInteger
	MinLavaDamage           mysql.ColumnInteger
	IdleWhenEmpty           mysql.ColumnInteger
	SecondsBeforeIdle       mysql.ColumnInteger
	ShardAtPlayerCount      mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type ZoneTable struct {
	zoneTable

	NEW zoneTable
}

// AS creates new ZoneTable with assigned alias
func (a ZoneTable) AS(alias string) *ZoneTable {
	return newZoneTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ZoneTable with assigned schema name
func (a ZoneTable) FromSchema(schemaName string) *ZoneTable {
	return newZoneTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ZoneTable with assigned table prefix
func (a ZoneTable) WithPrefix(prefix string) *ZoneTable {
	return newZoneTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ZoneTable with assigned table suffix
func (a ZoneTable) WithSuffix(suffix string) *ZoneTable {
	return newZoneTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newZoneTable(schemaName, tableName, alias string) *ZoneTable {
	return &ZoneTable{
		zoneTable: newZoneTableImpl(schemaName, tableName, alias),
		NEW:       newZoneTableImpl("", "new", ""),
	}
}

func newZoneTableImpl(schemaName, tableName, alias string) zoneTable {
	var (
		IDColumn                      = mysql.IntegerColumn("id")
		ZoneidnumberColumn            = mysql.IntegerColumn("zoneidnumber")
		VersionColumn                 = mysql.IntegerColumn("version")
		ShortNameColumn               = mysql.StringColumn("short_name")
		LongNameColumn                = mysql.StringColumn("long_name")
		MinStatusColumn               = mysql.IntegerColumn("min_status")
		MapFileNameColumn             = mysql.StringColumn("map_file_name")
		NoteColumn                    = mysql.StringColumn("note")
		MinExpansionColumn            = mysql.IntegerColumn("min_expansion")
		MaxExpansionColumn            = mysql.IntegerColumn("max_expansion")
		ContentFlagsColumn            = mysql.StringColumn("content_flags")
		ContentFlagsDisabledColumn    = mysql.StringColumn("content_flags_disabled")
		ExpansionColumn               = mysql.IntegerColumn("expansion")
		FileNameColumn                = mysql.StringColumn("file_name")
		SafeXColumn                   = mysql.FloatColumn("safe_x")
		SafeYColumn                   = mysql.FloatColumn("safe_y")
		SafeZColumn                   = mysql.FloatColumn("safe_z")
		SafeHeadingColumn             = mysql.FloatColumn("safe_heading")
		GraveyardIDColumn             = mysql.FloatColumn("graveyard_id")
		MinLevelColumn                = mysql.IntegerColumn("min_level")
		MaxLevelColumn                = mysql.IntegerColumn("max_level")
		TimezoneColumn                = mysql.IntegerColumn("timezone")
		MaxclientsColumn              = mysql.IntegerColumn("maxclients")
		RulesetColumn                 = mysql.IntegerColumn("ruleset")
		UnderworldColumn              = mysql.FloatColumn("underworld")
		MinclipColumn                 = mysql.FloatColumn("minclip")
		MaxclipColumn                 = mysql.FloatColumn("maxclip")
		FogMinclipColumn              = mysql.FloatColumn("fog_minclip")
		FogMaxclipColumn              = mysql.FloatColumn("fog_maxclip")
		FogBlueColumn                 = mysql.IntegerColumn("fog_blue")
		FogRedColumn                  = mysql.IntegerColumn("fog_red")
		FogGreenColumn                = mysql.IntegerColumn("fog_green")
		SkyColumn                     = mysql.IntegerColumn("sky")
		ZtypeColumn                   = mysql.IntegerColumn("ztype")
		ZoneExpMultiplierColumn       = mysql.FloatColumn("zone_exp_multiplier")
		WalkspeedColumn               = mysql.FloatColumn("walkspeed")
		TimeTypeColumn                = mysql.IntegerColumn("time_type")
		FogRed1Column                 = mysql.IntegerColumn("fog_red1")
		FogGreen1Column               = mysql.IntegerColumn("fog_green1")
		FogBlue1Column                = mysql.IntegerColumn("fog_blue1")
		FogMinclip1Column             = mysql.FloatColumn("fog_minclip1")
		FogMaxclip1Column             = mysql.FloatColumn("fog_maxclip1")
		FogRed2Column                 = mysql.IntegerColumn("fog_red2")
		FogGreen2Column               = mysql.IntegerColumn("fog_green2")
		FogBlue2Column                = mysql.IntegerColumn("fog_blue2")
		FogMinclip2Column             = mysql.FloatColumn("fog_minclip2")
		FogMaxclip2Column             = mysql.FloatColumn("fog_maxclip2")
		FogRed3Column                 = mysql.IntegerColumn("fog_red3")
		FogGreen3Column               = mysql.IntegerColumn("fog_green3")
		FogBlue3Column                = mysql.IntegerColumn("fog_blue3")
		FogMinclip3Column             = mysql.FloatColumn("fog_minclip3")
		FogMaxclip3Column             = mysql.FloatColumn("fog_maxclip3")
		FogRed4Column                 = mysql.IntegerColumn("fog_red4")
		FogGreen4Column               = mysql.IntegerColumn("fog_green4")
		FogBlue4Column                = mysql.IntegerColumn("fog_blue4")
		FogMinclip4Column             = mysql.FloatColumn("fog_minclip4")
		FogMaxclip4Column             = mysql.FloatColumn("fog_maxclip4")
		FogDensityColumn              = mysql.FloatColumn("fog_density")
		FlagNeededColumn              = mysql.StringColumn("flag_needed")
		CanbindColumn                 = mysql.IntegerColumn("canbind")
		CancombatColumn               = mysql.IntegerColumn("cancombat")
		CanlevitateColumn             = mysql.IntegerColumn("canlevitate")
		CastoutdoorColumn             = mysql.IntegerColumn("castoutdoor")
		HotzoneColumn                 = mysql.IntegerColumn("hotzone")
		InsttypeColumn                = mysql.IntegerColumn("insttype")
		ShutdowndelayColumn           = mysql.IntegerColumn("shutdowndelay")
		PeqzoneColumn                 = mysql.IntegerColumn("peqzone")
		BypassExpansionCheckColumn    = mysql.IntegerColumn("bypass_expansion_check")
		SuspendbuffsColumn            = mysql.IntegerColumn("suspendbuffs")
		RainChance1Column             = mysql.IntegerColumn("rain_chance1")
		RainChance2Column             = mysql.IntegerColumn("rain_chance2")
		RainChance3Column             = mysql.IntegerColumn("rain_chance3")
		RainChance4Column             = mysql.IntegerColumn("rain_chance4")
		RainDuration1Column           = mysql.IntegerColumn("rain_duration1")
		RainDuration2Column           = mysql.IntegerColumn("rain_duration2")
		RainDuration3Column           = mysql.IntegerColumn("rain_duration3")
		RainDuration4Column           = mysql.IntegerColumn("rain_duration4")
		SnowChance1Column             = mysql.IntegerColumn("snow_chance1")
		SnowChance2Column             = mysql.IntegerColumn("snow_chance2")
		SnowChance3Column             = mysql.IntegerColumn("snow_chance3")
		SnowChance4Column             = mysql.IntegerColumn("snow_chance4")
		SnowDuration1Column           = mysql.IntegerColumn("snow_duration1")
		SnowDuration2Column           = mysql.IntegerColumn("snow_duration2")
		SnowDuration3Column           = mysql.IntegerColumn("snow_duration3")
		SnowDuration4Column           = mysql.IntegerColumn("snow_duration4")
		GravityColumn                 = mysql.FloatColumn("gravity")
		TypeColumn                    = mysql.IntegerColumn("type")
		SkylockColumn                 = mysql.IntegerColumn("skylock")
		FastRegenHpColumn             = mysql.IntegerColumn("fast_regen_hp")
		FastRegenManaColumn           = mysql.IntegerColumn("fast_regen_mana")
		FastRegenEnduranceColumn      = mysql.IntegerColumn("fast_regen_endurance")
		NpcMaxAggroDistColumn         = mysql.IntegerColumn("npc_max_aggro_dist")
		ClientUpdateRangeColumn       = mysql.IntegerColumn("client_update_range")
		UnderworldTeleportIndexColumn = mysql.IntegerColumn("underworld_teleport_index")
		LavaDamageColumn              = mysql.IntegerColumn("lava_damage")
		MinLavaDamageColumn           = mysql.IntegerColumn("min_lava_damage")
		IdleWhenEmptyColumn           = mysql.IntegerColumn("idle_when_empty")
		SecondsBeforeIdleColumn       = mysql.IntegerColumn("seconds_before_idle")
		ShardAtPlayerCountColumn      = mysql.IntegerColumn("shard_at_player_count")
		allColumns                    = mysql.ColumnList{IDColumn, ZoneidnumberColumn, VersionColumn, ShortNameColumn, LongNameColumn, MinStatusColumn, MapFileNameColumn, NoteColumn, MinExpansionColumn, MaxExpansionColumn, ContentFlagsColumn, ContentFlagsDisabledColumn, ExpansionColumn, FileNameColumn, SafeXColumn, SafeYColumn, SafeZColumn, SafeHeadingColumn, GraveyardIDColumn, MinLevelColumn, MaxLevelColumn, TimezoneColumn, MaxclientsColumn, RulesetColumn, UnderworldColumn, MinclipColumn, MaxclipColumn, FogMinclipColumn, FogMaxclipColumn, FogBlueColumn, FogRedColumn, FogGreenColumn, SkyColumn, ZtypeColumn, ZoneExpMultiplierColumn, WalkspeedColumn, TimeTypeColumn, FogRed1Column, FogGreen1Column, FogBlue1Column, FogMinclip1Column, FogMaxclip1Column, FogRed2Column, FogGreen2Column, FogBlue2Column, FogMinclip2Column, FogMaxclip2Column, FogRed3Column, FogGreen3Column, FogBlue3Column, FogMinclip3Column, FogMaxclip3Column, FogRed4Column, FogGreen4Column, FogBlue4Column, FogMinclip4Column, FogMaxclip4Column, FogDensityColumn, FlagNeededColumn, CanbindColumn, CancombatColumn, CanlevitateColumn, CastoutdoorColumn, HotzoneColumn, InsttypeColumn, ShutdowndelayColumn, PeqzoneColumn, BypassExpansionCheckColumn, SuspendbuffsColumn, RainChance1Column, RainChance2Column, RainChance3Column, RainChance4Column, RainDuration1Column, RainDuration2Column, RainDuration3Column, RainDuration4Column, SnowChance1Column, SnowChance2Column, SnowChance3Column, SnowChance4Column, SnowDuration1Column, SnowDuration2Column, SnowDuration3Column, SnowDuration4Column, GravityColumn, TypeColumn, SkylockColumn, FastRegenHpColumn, FastRegenManaColumn, FastRegenEnduranceColumn, NpcMaxAggroDistColumn, ClientUpdateRangeColumn, UnderworldTeleportIndexColumn, LavaDamageColumn, MinLavaDamageColumn, IdleWhenEmptyColumn, SecondsBeforeIdleColumn, ShardAtPlayerCountColumn}
		mutableColumns                = mysql.ColumnList{ZoneidnumberColumn, VersionColumn, ShortNameColumn, LongNameColumn, MinStatusColumn, MapFileNameColumn, NoteColumn, MinExpansionColumn, MaxExpansionColumn, ContentFlagsColumn, ContentFlagsDisabledColumn, ExpansionColumn, FileNameColumn, SafeXColumn, SafeYColumn, SafeZColumn, SafeHeadingColumn, GraveyardIDColumn, MinLevelColumn, MaxLevelColumn, TimezoneColumn, MaxclientsColumn, RulesetColumn, UnderworldColumn, MinclipColumn, MaxclipColumn, FogMinclipColumn, FogMaxclipColumn, FogBlueColumn, FogRedColumn, FogGreenColumn, SkyColumn, ZtypeColumn, ZoneExpMultiplierColumn, WalkspeedColumn, TimeTypeColumn, FogRed1Column, FogGreen1Column, FogBlue1Column, FogMinclip1Column, FogMaxclip1Column, FogRed2Column, FogGreen2Column, FogBlue2Column, FogMinclip2Column, FogMaxclip2Column, FogRed3Column, FogGreen3Column, FogBlue3Column, FogMinclip3Column, FogMaxclip3Column, FogRed4Column, FogGreen4Column, FogBlue4Column, FogMinclip4Column, FogMaxclip4Column, FogDensityColumn, FlagNeededColumn, CanbindColumn, CancombatColumn, CanlevitateColumn, CastoutdoorColumn, HotzoneColumn, InsttypeColumn, ShutdowndelayColumn, PeqzoneColumn, BypassExpansionCheckColumn, SuspendbuffsColumn, RainChance1Column, RainChance2Column, RainChance3Column, RainChance4Column, RainDuration1Column, RainDuration2Column, RainDuration3Column, RainDuration4Column, SnowChance1Column, SnowChance2Column, SnowChance3Column, SnowChance4Column, SnowDuration1Column, SnowDuration2Column, SnowDuration3Column, SnowDuration4Column, GravityColumn, TypeColumn, SkylockColumn, FastRegenHpColumn, FastRegenManaColumn, FastRegenEnduranceColumn, NpcMaxAggroDistColumn, ClientUpdateRangeColumn, UnderworldTeleportIndexColumn, LavaDamageColumn, MinLavaDamageColumn, IdleWhenEmptyColumn, SecondsBeforeIdleColumn, ShardAtPlayerCountColumn}
		defaultColumns                = mysql.ColumnList{ZoneidnumberColumn, VersionColumn, MinStatusColumn, MinExpansionColumn, MaxExpansionColumn, ExpansionColumn, SafeXColumn, SafeYColumn, SafeZColumn, SafeHeadingColumn, GraveyardIDColumn, MinLevelColumn, MaxLevelColumn, TimezoneColumn, MaxclientsColumn, RulesetColumn, UnderworldColumn, MinclipColumn, MaxclipColumn, FogMinclipColumn, FogMaxclipColumn, FogBlueColumn, FogRedColumn, FogGreenColumn, SkyColumn, ZtypeColumn, ZoneExpMultiplierColumn, WalkspeedColumn, TimeTypeColumn, FogRed1Column, FogGreen1Column, FogBlue1Column, FogMinclip1Column, FogMaxclip1Column, FogRed2Column, FogGreen2Column, FogBlue2Column, FogMinclip2Column, FogMaxclip2Column, FogRed3Column, FogGreen3Column, FogBlue3Column, FogMinclip3Column, FogMaxclip3Column, FogRed4Column, FogGreen4Column, FogBlue4Column, FogMinclip4Column, FogMaxclip4Column, FogDensityColumn, FlagNeededColumn, CanbindColumn, CancombatColumn, CanlevitateColumn, CastoutdoorColumn, HotzoneColumn, InsttypeColumn, ShutdowndelayColumn, PeqzoneColumn, BypassExpansionCheckColumn, SuspendbuffsColumn, RainChance1Column, RainChance2Column, RainChance3Column, RainChance4Column, RainDuration1Column, RainDuration2Column, RainDuration3Column, RainDuration4Column, SnowChance1Column, SnowChance2Column, SnowChance3Column, SnowChance4Column, SnowDuration1Column, SnowDuration2Column, SnowDuration3Column, SnowDuration4Column, GravityColumn, TypeColumn, SkylockColumn, FastRegenHpColumn, FastRegenManaColumn, FastRegenEnduranceColumn, NpcMaxAggroDistColumn, ClientUpdateRangeColumn, UnderworldTeleportIndexColumn, LavaDamageColumn, MinLavaDamageColumn, IdleWhenEmptyColumn, SecondsBeforeIdleColumn, ShardAtPlayerCountColumn}
	)

	return zoneTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                      IDColumn,
		Zoneidnumber:            ZoneidnumberColumn,
		Version:                 VersionColumn,
		ShortName:               ShortNameColumn,
		LongName:                LongNameColumn,
		MinStatus:               MinStatusColumn,
		MapFileName:             MapFileNameColumn,
		Note:                    NoteColumn,
		MinExpansion:            MinExpansionColumn,
		MaxExpansion:            MaxExpansionColumn,
		ContentFlags:            ContentFlagsColumn,
		ContentFlagsDisabled:    ContentFlagsDisabledColumn,
		Expansion:               ExpansionColumn,
		FileName:                FileNameColumn,
		SafeX:                   SafeXColumn,
		SafeY:                   SafeYColumn,
		SafeZ:                   SafeZColumn,
		SafeHeading:             SafeHeadingColumn,
		GraveyardID:             GraveyardIDColumn,
		MinLevel:                MinLevelColumn,
		MaxLevel:                MaxLevelColumn,
		Timezone:                TimezoneColumn,
		Maxclients:              MaxclientsColumn,
		Ruleset:                 RulesetColumn,
		Underworld:              UnderworldColumn,
		Minclip:                 MinclipColumn,
		Maxclip:                 MaxclipColumn,
		FogMinclip:              FogMinclipColumn,
		FogMaxclip:              FogMaxclipColumn,
		FogBlue:                 FogBlueColumn,
		FogRed:                  FogRedColumn,
		FogGreen:                FogGreenColumn,
		Sky:                     SkyColumn,
		Ztype:                   ZtypeColumn,
		ZoneExpMultiplier:       ZoneExpMultiplierColumn,
		Walkspeed:               WalkspeedColumn,
		TimeType:                TimeTypeColumn,
		FogRed1:                 FogRed1Column,
		FogGreen1:               FogGreen1Column,
		FogBlue1:                FogBlue1Column,
		FogMinclip1:             FogMinclip1Column,
		FogMaxclip1:             FogMaxclip1Column,
		FogRed2:                 FogRed2Column,
		FogGreen2:               FogGreen2Column,
		FogBlue2:                FogBlue2Column,
		FogMinclip2:             FogMinclip2Column,
		FogMaxclip2:             FogMaxclip2Column,
		FogRed3:                 FogRed3Column,
		FogGreen3:               FogGreen3Column,
		FogBlue3:                FogBlue3Column,
		FogMinclip3:             FogMinclip3Column,
		FogMaxclip3:             FogMaxclip3Column,
		FogRed4:                 FogRed4Column,
		FogGreen4:               FogGreen4Column,
		FogBlue4:                FogBlue4Column,
		FogMinclip4:             FogMinclip4Column,
		FogMaxclip4:             FogMaxclip4Column,
		FogDensity:              FogDensityColumn,
		FlagNeeded:              FlagNeededColumn,
		Canbind:                 CanbindColumn,
		Cancombat:               CancombatColumn,
		Canlevitate:             CanlevitateColumn,
		Castoutdoor:             CastoutdoorColumn,
		Hotzone:                 HotzoneColumn,
		Insttype:                InsttypeColumn,
		Shutdowndelay:           ShutdowndelayColumn,
		Peqzone:                 PeqzoneColumn,
		BypassExpansionCheck:    BypassExpansionCheckColumn,
		Suspendbuffs:            SuspendbuffsColumn,
		RainChance1:             RainChance1Column,
		RainChance2:             RainChance2Column,
		RainChance3:             RainChance3Column,
		RainChance4:             RainChance4Column,
		RainDuration1:           RainDuration1Column,
		RainDuration2:           RainDuration2Column,
		RainDuration3:           RainDuration3Column,
		RainDuration4:           RainDuration4Column,
		SnowChance1:             SnowChance1Column,
		SnowChance2:             SnowChance2Column,
		SnowChance3:             SnowChance3Column,
		SnowChance4:             SnowChance4Column,
		SnowDuration1:           SnowDuration1Column,
		SnowDuration2:           SnowDuration2Column,
		SnowDuration3:           SnowDuration3Column,
		SnowDuration4:           SnowDuration4Column,
		Gravity:                 GravityColumn,
		Type:                    TypeColumn,
		Skylock:                 SkylockColumn,
		FastRegenHp:             FastRegenHpColumn,
		FastRegenMana:           FastRegenManaColumn,
		FastRegenEndurance:      FastRegenEnduranceColumn,
		NpcMaxAggroDist:         NpcMaxAggroDistColumn,
		ClientUpdateRange:       ClientUpdateRangeColumn,
		UnderworldTeleportIndex: UnderworldTeleportIndexColumn,
		LavaDamage:              LavaDamageColumn,
		MinLavaDamage:           MinLavaDamageColumn,
		IdleWhenEmpty:           IdleWhenEmptyColumn,
		SecondsBeforeIdle:       SecondsBeforeIdleColumn,
		ShardAtPlayerCount:      ShardAtPlayerCountColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
