package zone

// AnimationDefinitions defines animation constants
type AnimationDefinitions struct{}

const (
	None               = "pos"
	Kick               = "c01"
	Pierce1h           = "c02"
	Slash2h            = "c03"
	Blunt2h            = "c04"
	Slash1h            = "c05"
	SlashOffhand1h     = "c06"
	Bash               = "c07"
	HandToHandPrimary  = "c08"
	Archery            = "c09"
	Swimming1          = "c10"
	RoundhouseKick     = "c11"
	MinorDamage        = "d01"
	HeavyDamage        = "d02"
	Drowning           = "d04"
	Death              = "d05"
	Walking            = "l01"
	Running            = "l02"
	RunningJump        = "l03"
	StationaryJump     = "l04"
	Falling            = "l05"
	DuckWalking        = "l06"
	LadderClimbing     = "l07"
	DuckDown           = "l08"
	SwimmingStationary = "l09"
	Idle2              = "o01"
	Idle1              = "p01"
	SitDown            = "p02"
	ShuffleRotate      = "p03"
	ShuffleStrafe      = "p04"
	Loot               = "p05"
	Swimming2          = "p06"
	Cheer              = "s01"
	Disappointed       = "s02"
	Wave               = "s03"
	Rude               = "s04"
	StringedInstrument = "t02"
	WoodwindInstrument = "t03"
	Cast1              = "t04"
	Cast2              = "t05"
	Cast3              = "t06"
	FlyingKick         = "t07"
	TigerStrike        = "t08"
	DragonPunch        = "t09"
	// Socials
	Nod     = "s06"
	Amaze   = "s07"
	Plead   = "s08"
	Clap    = "s09"
	Hungry  = "s10"
	Blush   = "s11"
	Chuckle = "s12"
	Cough   = "s13"
	Duck    = "s14"
	Puzzle  = "s15"
	Dance   = "s16"
	Blink   = "s17"
	Glare   = "s18"
	Drool   = "s19"
	Kneel   = "s20"
	Laugh   = "s21"
	Point   = "s22"
	Shrug   = "s23"
	Ready   = "s24"
	Salute  = "s25"
	Shiver  = "s26"
	Tap     = "s27"
	Bow     = "s28"
)
